package com.example.adbtoolbox.common

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object AppSettings {
    var isDarkMode by mutableStateOf(true)
    var language by mutableStateOf("zh") // "zh" or "en" or "hi"
    var navIndicatorStyle by mutableStateOf("capsule") // "capsule"=capsule shape, "round"=round shape
    var shizukuAutoActivate by mutableStateOf(false) // Shizuku auto activate

    fun toggleDarkMode() {
        isDarkMode = !isDarkMode
    }

    fun toggleNavIndicatorStyle() {
        navIndicatorStyle = if (navIndicatorStyle == "capsule") "round" else "capsule"
    }

    fun getNavIndicatorHeight(): Float {
        return if (navIndicatorStyle == "capsule") 50f else 56f
    }
}

// Simple multi-language text mapping (zh/en/hi)
object AppStrings {
    fun get(key: String): String {
        return when (AppSettings.language) {
            "en" -> enStrings[key] ?: key
            "hi" -> hiStrings[key] ?: (enStrings[key] ?: key)
            else -> zhStrings[key] ?: key
        }
    }

    private val zhStrings = mapOf(
        // 通用
        "settings" to "设置",
        "home" to "主页",
        "enabled" to "开启",
        "disabled" to "关闭",
        "glass_effect" to "液态玻璃",
        "glass_playground" to "液态玻璃调节",
        "glass_playground_hint" to "实时调节液态玻璃效果参数",
        "corner_radius" to "圆角",
        "blur_radius" to "模糊半径",
        "refraction_height" to "折射高度",
        "refraction_amount" to "折射量",
        "chromatic_aberration" to "色差",
        "vibrancy" to "光域效果",
        "global_intensity" to "全局渲染强度",
        "global_intensity_hint" to "增强所有液态玻璃的折射与模糊实时渲染效果",
        "long_press_effect" to "长按发光效果",
        "long_press_glow_intensity" to "发光强度",
        "long_press_glow_size" to "光晕大小",
        "long_press_refraction" to "边缘折射",
        "long_press_glow_hint" to "长按胶囊或玻璃滑块，边缘会发光并产生折射扭曲效果",
"font_color" to "字体颜色",
"color_default" to "默认",
"color_white" to "白色",
"color_black" to "黑色",
"color_red" to "赤",
"color_orange" to "橙",
"color_yellow" to "黄",
"color_green" to "绿",
"color_cyan" to "青",
"color_blue" to "蓝",
"color_purple" to "紫",
        "color_pink" to "粉色",
        "color_brown" to "棕色",
        "color_gray" to "灰色",
        "color_dark_red" to "深红",
        "color_dark_orange" to "深橙",
        "color_dark_green" to "深绿",
        "color_dark_blue" to "深蓝",
        "color_dark_purple" to "深紫",
        "color_light_red" to "浅红",
        "color_light_orange" to "浅橙",
        "color_light_yellow" to "浅黄",
        "color_light_green" to "浅绿",
        "color_light_blue" to "浅蓝",
        "color_light_purple" to "浅紫",
        "color_orange_red" to "橙红",
        "color_yellow_green" to "黄绿",
        "color_teal" to "蓝绿",
        "color_indigo" to "靛蓝",
        "color_magenta" to "品红",
        "color_gold" to "金色",
        "color_silver" to "银色",
        "color_cream" to "米白",
        "glass_color" to "玻璃颜色",
        "save" to "保存设置",
        "saved" to "✓ 已保存",
        "plugins_hint" to "AxManager 风格插件：支持 zip 插件包，可包含脚本、WebUI 和系统配置",
        "installing" to "安装中...",
        "no_plugins" to "暂无插件",
        "no_plugins_hint" to "点击右上角安装按钮选择 zip 插件包",
        "install_plugin" to "安装插件",
        "apps" to "应用",
        "terminal" to "终端",
        "back" to "返回",
        "loading" to "加载中...",
        "execute" to "执行",
        "clear" to "清空",
        "output" to "输出",
        "adb_toolbox" to "ADB工具箱",

        // Shizuku
        "shizuku_service" to "Shizuku 服务",
        "shizuku_connected" to "已连接 - ADB 权限可用",
        "shizuku_disconnected" to "未连接 - 部分功能受限",
        "shizuku_not_connected" to "Shizuku 未连接",
        "request_shizuku" to "请求 Shizuku 权限",
        "shizuku_permission_granted" to "Shizuku 权限已授予",
        "shizuku_permission_denied" to "Shizuku 权限被拒绝",
        "wireless_debugging_hint" to "请在开发者选项中开启无线调试",
        "authorization_required" to "需要授权才能使用此功能",

        // 显示设置
        "display_settings" to "显示设置",
        "dark_mode" to "深色模式",
        "light_mode" to "浅色模式",
        "language" to "语言",
        "chinese" to "中文",
        "english" to "English",
        "wallpaper" to "壁纸",
        "set_wallpaper" to "设置壁纸",
        "screen_brightness" to "屏幕亮度",
        "screen_timeout" to "屏幕超时",

        // 系统操作
        "system_actions" to "系统操作",
        "reboot" to "重启",
        "recovery" to "Recovery",
        "bootloader" to "Bootloader",
        "shutdown" to "关机",
        "restart_systemui" to "重启SystemUI",
        "screenshot" to "截屏",

        // 设备信息
        "device_info" to "设备信息",
        "model" to "型号",
        "brand" to "品牌",
        "android_version" to "Android版本",
        "sdk" to "SDK",
        "memory" to "内存",
        "storage" to "存储",
        "battery" to "电池",
        "refresh_rate" to "刷新率",
        "root" to "Root",
        "root_obtained" to "root 权限已授予",
        "root_not_obtained" to "未获取 root 权限",
        "view_details" to "查看详情",
        "cpu_info" to "CPU信息",
        "cpu_cores" to "CPU核心",
        "screen_resolution" to "屏幕分辨率",
        "kernel_version" to "内核版本",

        // 快捷功能
        "quick_actions" to "快捷功能",
        "adb_panel" to "ADB面板",
        "permissions" to "权限管理",
        "root_manager" to "Root管理",
        "shell_executor" to "Shell执行",
        "app_manager" to "应用管理",

        // ADB面板
        "adb_quick_panel" to "ADB快捷面板",
        "device_control" to "设备控制",
        "system_settings" to "系统设置",
        "enable_adb" to "开启ADB",
        "disable_adb" to "关闭ADB",
        "install_unknown_apps" to "安装未知应用",
        "cleanup_operations" to "清理操作",
        "clean_all_cache" to "清理所有缓存",
        "clean_logcat" to "清理Logcat",

        // 应用管理
        "show_system_apps" to "显示系统应用",
        "system_app" to "系统应用",
        "user_app" to "用户应用",
        "type" to "类型",
        "status" to "状态",
        "normal" to "正常",
        "frozen" to "已冻结",
        "not_frozen" to "未冻结",
        "version" to "版本",
        "package_name" to "包名",
        "freeze" to "冻结",
        "unfreeze" to "解冻",
        "uninstall" to "卸载",
        "clear_cache" to "清缓存",
        "force_stop" to "强停",
        "app_actions" to "应用操作",
        "app_permissions" to "权限",
        "app_detail" to "应用详情",

        // 权限管理
        "permission_manager" to "权限管理",
        "granted" to "已授权",
        "not_granted" to "未授权",
        "grant" to "授权",
        "revoke" to "撤销",

        // Root管理
        "root_status" to "Root状态",
        "root_permission" to "Root权限",
        "su_version" to "Su版本",
        "busybox_version" to "BusyBox版本",
        "request_root" to "请求Root权限",
        "verify_root" to "验证Root权限",
        "root_verified" to "Root权限验证成功",
        "root_verify_failed" to "Root权限验证失败",
        "root_quick_commands" to "Root快捷命令",
        "view_uid" to "查看UID",
        "mount_rw" to "挂载读写",
        "mount_ro" to "挂载只读",
        "modify_hosts" to "修改hosts",
        "clear_data" to "清除数据",
        "view_processes" to "查看进程",
        "execution_result" to "执行结果",
        "exit_code" to "退出码",
        "error_output" to "错误",

        // Shell/终端
        "shell_executor_title" to "Shell执行",
        "terminal_title" to "终端",
        "adb_module" to "ADB模块",
        "adb_plugins" to "ADB插件",
        "root_module" to "Root模块",
        "module_hint" to "选择 zip 格式的 Magisk/KernelSU 模块文件进行刷入。需要 Root 权限。",
        "select_module_file" to "选择模块文件",
        "choose_file" to "选择文件",
        "no_file_selected" to "未选择文件",
        "flash_module" to "刷入模块",
        "module_installing" to "正在刷入...",
        "install_log" to "刷入日志",
        "plugins" to "插件",
        "install_plugin" to "安装插件",
        "no_plugins" to "暂无插件",
        "no_plugins_hint" to "点击右上角安装 AxManager 风格插件",
        "author" to "作者",
        "enabled" to "已启用",
        "disabled" to "已禁用",
        "enable" to "启用",
        "disable" to "禁用",
        "uninstall" to "卸载",
        "run_action" to "运行",
        "action_output" to "运行输出",
        "actions" to "操作",
        "flash_mode" to "刷入模式",
        "adb_mode" to "ADB模式",
        "root_mode" to "Root模式",
        "adb_mode_hint" to "使用 Shizuku/ADB 权限刷入，无需 Root。支持 Magisk 模块脚本执行和 APK 安装。",
        "root_mode_hint" to "使用 Root 权限刷入 Magisk/KernelSU 模块。需要设备已 Root 并安装 Magisk 或 KernelSU。",
        "adb_terminal_hint" to "ADB 终端 - 输入命令执行",
        "enter_command" to "输入命令...",
        "command_history" to "命令历史",
        "clear_screen" to "清屏",
        "diagnose" to "诊断",
        "execute_btn" to "执行",

        // 操作结果
        "success" to "成功",
        "failed" to "失败",
        "operation_failed" to "操作失败",
        "app_frozen" to "应用已冻结",
        "app_unfrozen" to "应用已解冻",
        "app_uninstalled" to "应用已卸载",
        "cache_cleared" to "缓存已清理",
        "app_force_stopped" to "应用已强制停止",
        "permission_granted" to "权限已授予",
        "permission_revoked" to "权限已撤销",
        "brightness_set" to "亮度已设置",
        "timeout_set" to "超时已设置",
        "rebooting" to "正在重启...",
        "wallpaper_set" to "壁纸已设置",

        // 日志
        "logcat" to "Logcat",
        "clear_logcat_done" to "Logcat已清理",

        // 新增
        "executing" to "执行中",
        "need_root_or_shizuku" to "需要Root或Shizuku",
        "allowed" to "允许",
        "denied" to "拒绝",
        "more_items" to "还有",
        "hindi" to "हिन्दी",

        // 动态壁纸
        "dynamic_wallpaper" to "动态壁纸",
        "splash_animation" to "开屏动画",
        "splash_video_hint" to "使用视频作为开屏动画，自动适配各种分辨率（2K 等），帧率跟随视频本身",
        "splash_select_video" to "选择开屏视频",
        "splash_video_selected" to "已设置开屏视频",
        "splash_current" to "当前开屏视频",
        "splash_clear" to "恢复默认开屏",
        "enable_dynamic_wallpaper" to "启用动态壁纸",
        "video_file" to "视频文件",
        "select_video" to "选择视频文件",
        "video_selected" to "已选择视频，点击更换",
        "current_video" to "当前视频:",
        "video_hint" to "支持 MP4、3GP 等常见视频格式，将作为应用背景循环播放",
        "delete_video" to "删除视频",

        // 液态玻璃调节
        "home_glass" to "主页液态玻璃",
        "terminal_glass" to "终端液态玻璃",
        "settings_glass" to "设置页面液态玻璃",
        "apps_glass" to "应用管理液态玻璃",
        "adbmodule_glass" to "ADB模块页面玻璃",
        "plugins_glass" to "插件页面玻璃",

        // 导航栏胶囊调节
        "nav_capsule_settings" to "导航栏胶囊调节",
        "capsule_shape" to "胶囊形状",
        "round" to "圆球",
        "square" to "正方形",
        "capsule" to "胶囊",
        "capsule_height" to "胶囊高度",
        "capsule_width" to "胶囊宽度",
        "auto" to "自适应",
        "capsule_corner" to "胶囊圆角",
        "capsule_blur" to "胶囊模糊",
        "capsule_opacity" to "胶囊透明度",

        // 导航栏液态玻璃
        "nav_glass" to "导航栏液态玻璃",
        "refraction_height" to "折射高度",
        "refraction_amount" to "折射量",
        "opacity" to "透明度",

        // Root 工具
        "root_tool" to "一键 Root 工具",
        "temp_root" to "临时 Root",
        "root_tool_hint" to "支持 Magisk / KernelSU / 临时 Root",
        "detecting" to "检测中...",
        "select_root_method" to "选择 Root 方案",
        "exec_progress" to "执行进度",
        "redetect" to "重新检测设备",
        "not_supported" to "暂不支持",
        "risk_warning" to "⚠️ 风险提示",

        // Dhizuku
        "use_dhizuku" to "使用 Dhizuku 权限",
        "dhizuku_hint" to "比 Shizuku 更小一层的权限，基于设备所有者",
        "dhizuku_notice" to "注意：激活前请确保设备上没有其他账户（包括双开空间）",
        "dhizuku_activate_hint" to "请通过 ADB 激活 Dhizuku 为设备所有者",
        "dhizuku_not_active" to "Dhizuku 未激活",
        "dhizuku_install_hint" to "请先安装 Dhizuku 应用",
        "dhizuku_denied" to "Dhizuku 权限被拒绝",
        "dhizuku_granted" to "Dhizuku 权限已授予",
        "dhizuku_requesting" to "正在请求...",
        "dhizuku_request" to "请求 Dhizuku 权限",
        "dhizuku_not_installed" to "Dhizuku 未安装",
        "dhizuku_active" to "已激活为设备所有者",
        "dhizuku_inactive" to "已安装但未激活",
        "dhizuku_activating" to "正在激活 Dhizuku...",
        "dhizuku_activate" to "激活 Dhizuku",
        "dhizuku_removing" to "正在移除 Dhizuku...",
        "dhizuku_remove" to "移除 Dhizuku",

        // Shell 执行器
        "use_root" to "使用 Root 执行",
        "shell_input_hint" to "输入 Shell 命令...",
        "quick_commands" to "快捷命令",

        // Root 设备信息
        "brand" to "品牌",
        "model" to "型号",
        "device_codename" to "设备代号",
        "android_version" to "安卓版本",
        "kernel_version" to "内核版本",
        "bl_status" to "BL解锁状态",
        "unlocked" to "已解锁",
        "locked" to "未解锁",
        "gki_device" to "GKI设备",
        "yes" to "是",
        "no" to "否",
        "rooted" to "已Root",
        "temp_root" to "临时Root",
        "unknown" to "未知",
        "supported" to "支持",
        "temp_root_vuln" to "临时 Root（漏洞）",
        "magisk_desc" to "修补 boot.img，支持模块系统",
        "kernelsu_desc" to "内核级 root，性能更好",
        "temproot_desc" to "基于漏洞，重启失效，无需解锁BL",
        "checking_device" to "正在检测设备...",
        "extracting_boot" to "正在提取 boot.img...",
        "patching_boot" to "正在修补 boot.img...",
        "flashing_boot" to "正在刷入 boot.img...",
        "rebooting" to "正在重启设备...",
        "op_success" to "操作成功",
        "op_failed" to "操作失败",
        "start_root" to "开始 Root",
        "executing" to "执行中...",
        "unsupported_msg" to "当前设备不支持一键 Root。请确保：\n1. 已解锁 Bootloader\n2. 设备支持 Magisk 或 KernelSU\n3. 或使用支持临时 Root 的机型",
        "risk_msg" to "1. Root 操作可能导致设备变砖，请谨慎操作\n2. Root 后将失去官方保修\n3. 部分银行/支付应用可能无法使用\n4. 建议先备份重要数据\n5. 临时 Root 基于公开漏洞，重启后失效\n6. Magisk/KernelSU 需要解锁 Bootloader",
        "ghostlock" to "GhostLock (一加)",
        "temproot_xiaomi" to "TempRoot (小米)",
        "msg_extract_boot" to "提取 boot.img...",
        "msg_patch_magisk" to "使用 Magisk 修补 boot.img...",
        "msg_flash_boot" to "刷入修补后的 boot.img...",
        "msg_temp_root" to "执行临时 Root...",
        "msg_check_ksu" to "正在检测 KernelSU...",
        "msg_no_ksu" to "未检测到 KernelSU，正在打开终端...",
        "msg_error_prefix" to "出错了: ",
        "waiting_cmd" to "等待执行命令...",
        "err_bracket" to "[错误]",
        "exit_code_bracket" to "[退出码: ",
        "ksu_terminal_banner" to "  KernelSU 未检测到",
        "ksu_terminal_website" to "KernelSU 官网: ",
        "ksu_terminal_copy" to "请复制上方网址到浏览器下载 KernelSU",
        "ksu_terminal_open" to "或使用以下命令直接打开:",
        "ksu_terminal_tried" to "已尝试打开浏览器，如果未打开请手动复制网址",

        // 壁纸操作
        "clear_wallpaper" to "删除壁纸",
        "wallpaper_cleared" to "壁纸已删除",
        "performance_boost" to "性能加速",
        "performance_boost_hint" to "基于本机品牌自动匹配真实可执行的 ADB 指令，一键提升性能",
        "phone_inspector" to "手机体检",
        "phone_inspector_hint" to "检测机型与系统，逐项验证哪些指令在本机真的可用",
        "not_recognized_brand" to "未识别的品牌",
        "brand_specific_count" to "条品牌专属优化",
        "generic_count" to "条通用优化",
        "run_selected" to "执行选中项",
        "run_all" to "全部执行",
        "one_tap_boost" to "一键加速",
        "select_all" to "全选",
        "select_none" to "全不选",
        "selected_count" to "已选 %1\$d 项",
        "running_item" to "正在执行",
        "run_progress" to "进度 %1\$d / %2\$d",
        "boost_done_title" to "加速完成",
        "boost_success_count" to "成功 %1\$d 项",
        "boost_failed_count" to "失败 %2\$d 项",
        "freed_memory" to "释放内存 %1\$d MB",
        "used_time" to "耗时 %1\$d ms",
        "hide_details" to "收起详情",
        "requires_root" to "需要 Root",
        "requires_shizuku" to "需要 Shizuku",
        "risk_safe" to "安全",
        "risk_caution" to "谨慎",
        "risk_risky" to "高风险",
        "confirm_run_risky" to "该项为高风险操作，确定继续？",
        "confirm_run" to "确定执行",
        "cancel" to "取消",
        "run_failed_reason" to "失败原因",
        "no_permission_hint" to "未检测到 Shizuku 或 Root 权限，部分指令无法生效",
        "grant_shizuku" to "授予 Shizuku 权限",
        "go_to_settings" to "前往设置",
        "execute_fix" to "执行修复",
        "inspect_running" to "正在检测",
        "inspect_phase" to "检测阶段 %1\$d / %2\$d",
        "inspect_score" to "综合得分",
        "inspect_ok_count" to "正常 %1\$d 项",
        "inspect_warn_count" to "待优化 %1\$d 项",
        "inspect_fail_count" to "不可用 %1\$d 项",
        "re_inspect" to "重新体检",
        "inspect_device_summary" to "机型信息",
        "inspect_fix_all" to "一键优化全部",
        "inspect_all_fixed" to "已提交 %1\$d 项优化",
        "inspect_group_device" to "设备与系统",
        "inspect_group_perf" to "性能相关设置",
        "inspect_group_brand" to "品牌专属能力",
        "inspect_group_refresh" to "屏幕刷新率",
        "inspect_group_root" to "Root / Shizuku 环境",
        "not_detected" to "未检测到",
        "available" to "可用",
        "configured" to "已配置",
        "not_configured" to "未配置",
        "unsupported" to "本机不支持",
        "refresh_rate_fix" to "修复刷新率",
        "refresh_rate_detail" to "当前 %1\$s / 最高 %2\$s，支持：%3\$s",
        "refresh_rate_supported" to "支持档位",
        "refresh_rate_reset" to "恢复自适应",
        "refresh_rate_fixed" to "刷新率已修复",
        "refresh_rate_confirm" to "将把屏幕刷新率强制调到最高档，可能增加耗电。确定继续？",
        "perf_cat_background" to "后台进程",
        "perf_cat_animation" to "动画速度",
        "perf_cat_cpu" to "处理器与调度",
        "perf_cat_memory" to "内存与缓存",
        "perf_cat_power" to "电源管理",
        "perf_cat_network" to "网络栈",
        "perf_cat_storage" to "存储与数据库",
        "perf_cat_display" to "显示与刷新率",
        "perf_cat_brand" to "品牌专属调优",
        "brand_generic" to "通用 Android",
        "brand_xiaomi" to "小米 / Redmi / POCO",
        "brand_huawei" to "华为",
        "brand_honor" to "荣耀",
        "brand_oppo" to "OPPO",
        "brand_realme" to "realme",
        "brand_vivo" to "vivo",
        "brand_iqoo" to "iQOO",
        "brand_oneplus" to "一加",
        "brand_samsung" to "三星",
        "brand_meizu" to "魅族",
        "brand_nubia" to "努比亚 / 红魔",
        "brand_asus" to "华硕 ROG",
        "brand_sony" to "索尼",
        "brand_motorola" to "摩托罗拉",
        "brand_google" to "Google Pixel",
        "perf_item_kill_bg" to "结束全部后台进程",
        "perf_item_kill_bg_desc" to "am kill-all，清理所有可回收的后台进程，无需 Root",
        "perf_item_trim_caches" to "清理全部应用缓存",
        "perf_item_trim_caches_desc" to "pm trim-caches，释放所有应用的缓存占用",
        "perf_item_compact_bg" to "压缩后台内存",
        "perf_item_compact_bg_desc" to "对系统进程执行内存压缩，缓解内存压力（Android 12+）",
        "perf_item_drop_caches" to "清空内核页缓存",
        "perf_item_drop_caches_desc" to "drop_caches=3，释放内核缓存页，需要 Root",
        "perf_item_anim_scale_off" to "动画加速至 0.5x",
        "perf_item_anim_scale_off_desc" to "窗口/过渡/动画时长全部调为 0.5x，操作响应明显变快，可恢复",
        "perf_item_anim_scale_zero" to "关闭动画（0x）",
        "perf_item_anim_scale_zero_desc" to "彻底关闭动画，速度最快，但观感会变生硬，可恢复",
        "perf_item_cpu_force_gpu" to "强制 GPU 渲染",
        "perf_item_cpu_force_gpu_desc" to "强制使用 GPU 渲染界面，减轻 CPU 负担（部分机型可能闪烁）",
        "perf_item_cpu_disable_low_power" to "退出省电模式",
        "perf_item_cpu_disable_low_power_desc" to "关闭低电量模式并解除 CPU 降频",
        "perf_item_cpu_perf_mode" to "CPU 调度改 performance",
        "perf_item_cpu_perf_mode_desc" to "所有核心调度器切到 performance，性能拉满但发热耗电明显，需要 Root",
        "perf_item_cpu_min_freq_max" to "锁定 CPU 最低频率为最高频",
        "perf_item_cpu_min_freq_max_desc" to "把 scaling_min_freq 拉到 cpuinfo_max_freq，避免降频，需要 Root",
        "perf_item_cpu_stop_thermal" to "停止温控服务",
        "perf_item_cpu_stop_thermal_desc" to "停止厂商温控守护进程，避免高温降频；有硬件损伤风险，需要 Root",
        "perf_item_cpu_setenforce_zero" to "SELinux 切换为宽容模式",
        "perf_item_cpu_setenforce_zero_desc" to "setenforce 0，解除部分权限限制；安全性下降，需要 Root",
        "perf_item_mem_disable_zram" to "关闭 ZRAM 交换",
        "perf_item_mem_disable_zram_desc" to "关闭内存压缩交换，降低 CPU 占用；低内存机型可能更容易杀后台，需要 Root",
        "perf_item_mem_vfs_pressure" to "优化内核内存参数",
        "perf_item_mem_vfs_pressure_desc" to "调整 vfs_cache_pressure 与脏页回写阈值，需要 Root",
        "perf_item_mem_lmk_protect" to "调整低内存杀手阈值",
        "perf_item_mem_lmk_protect_desc" to "放宽 LMK 参数，减少后台被杀，需要 Root",
        "perf_item_power_saver_off" to "关闭省电与 Doze",
        "perf_item_power_saver_off_desc" to "关闭省电模式与 Doze 深度休眠，后台不再被冻结",
        "perf_item_power_unrestrict" to "解除 SystemUI 后台限制",
        "perf_item_power_unrestrict_desc" to "把 SystemUI 加入 Doze 白名单并允许后台运行，减少卡顿",
        "perf_item_power_adb_wifi_off" to "关闭 Wi-Fi 与移动数据",
        "perf_item_power_adb_wifi_off_desc" to "svc 关闭无线与数据，纯粹省电，可恢复",
        "perf_item_net_tcp_fast" to "优化 TCP 缓冲区",
        "perf_item_net_tcp_fast_desc" to "调大 TCP 收发缓冲区，改善高延迟网络吞吐，需要 Root",
        "perf_item_net_dns_flush" to "刷新 DNS 缓存",
        "perf_item_net_dns_flush_desc" to "清空 netd 解析缓存，解决域名解析异常",
        "perf_item_storage_vacuum" to "整理应用数据库",
        "perf_item_storage_vacuum_desc" to "对所有应用 SQLite 执行 VACUUM，减小体积提升读写，需要 Root 且耗时",
        "perf_item_storage_fstrim" to "执行闪存 TRIM",
        "perf_item_storage_fstrim_desc" to "fstrim 回收闪存空闲块，改善长期使用后的写入掉速，需要 Root",
        "perf_item_storage_drop_logs" to "清理日志与崩溃记录",
        "perf_item_storage_drop_logs_desc" to "清空 logcat 与 anr/tombstones，释放空间",
        "perf_item_display_max_refresh" to "解锁屏幕最高刷新率",
        "perf_item_display_max_refresh_desc" to "自动读取本机支持的最高刷新率并写入 peak_refresh_rate，修复锁 60Hz",
        "perf_item_display_force_high_refresh" to "强制固定 120Hz",
        "perf_item_display_force_high_refresh_desc" to "把峰值与最低刷新率都写为 120Hz，全程高刷；非 120Hz 屏幕会回退",
        "perf_item_display_aod_off" to "关闭息屏显示",
        "perf_item_display_aod_off_desc" to "关闭 AOD 常亮显示，降低熄屏功耗，可恢复",
        "perf_item_mi_optimization_on" to "开启 MIUI 优化",
        "perf_item_mi_optimization_on_desc" to "打开 mi_optimization，关闭云同步与查找设备自动同步",
        "perf_item_mi_kill_background" to "关闭后台进程限制",
        "perf_item_mi_kill_background_desc" to "background_process_limit=0 并立即 am kill-all",
        "perf_item_mi_disable_powerkeeper" to "放宽 PowerKeeper 限制",
        "perf_item_mi_disable_powerkeeper_desc" to "提高各核功耗检查上限，减少被 PowerKeeper 限制性能",
        "perf_item_mi_disable_joyose" to "停用 Joyose 云控",
        "perf_item_mi_disable_joyose_desc" to "禁用 com.xiaomi.joyose 云控调频，游戏帧率更稳，可恢复",
        "perf_item_mi_disable_analytics" to "停用小米广告与统计",
        "perf_item_mi_disable_analytics_desc" to "禁用 analytics / mipicks / msa / metoknlp，减少后台唤醒，可恢复",
        "perf_item_mi_gpu_tuning" to "开启游戏加速",
        "perf_item_mi_gpu_tuning_desc" to "强制 skiagl 渲染并开启游戏turbo模式",
        "perf_item_mi_ram_expansion_off" to "关闭内存扩展",
        "perf_item_mi_ram_expansion_off_desc" to "关闭 ZRAM 内存扩展，需要 Root",
        "perf_item_hw_disable_powergenie" to "停用华为 PowerGenie",
        "perf_item_hw_disable_powergenie_desc" to "禁用 com.huawei.powergenie 激进省电策略，可恢复",
        "perf_item_hw_disable_analytics" to "停用华为统计服务",
        "perf_item_hw_disable_analytics_desc" to "禁用 hwaps / bd / microkernel 统计上报，可恢复",
        "perf_item_hw_perf_mode" to "开启华为性能模式",
        "perf_item_hw_perf_mode_desc" to "写入 hw_power_mode=1 性能模式",
        "perf_item_hw_kill_bg" to "清理华为后台进程",
        "perf_item_hw_kill_bg_desc" to "am kill-all 清理后台",
        "perf_item_hw_gpu_turbo" to "开启 GPU Turbo",
        "perf_item_hw_gpu_turbo_desc" to "强制 GPU 渲染并开启 GPU Turbo 标记，需要 Root",
        "perf_item_oppo_perf_mode" to "开启 ColorOS 性能模式",
        "perf_item_oppo_perf_mode_desc" to "写入 oppo_performance_mode 与游戏模式",
        "perf_item_oppo_disable_power" to "停用 OPPO 省电守护",
        "perf_item_oppo_disable_power_desc" to "禁用 oppoguardelf 省电守护，可恢复",
        "perf_item_oppo_disable_analytics" to "停用 OPPO 日志统计",
        "perf_item_oppo_disable_analytics_desc" to "禁用 logkit / usageassist 日志上报，可恢复",
        "perf_item_oppo_kill_bg" to "清理 ColorOS 后台进程",
        "perf_item_oppo_kill_bg_desc" to "am kill-all 清理后台",
        "perf_item_oppo_disable_osense" to "停用 oSense 调度",
        "perf_item_oppo_disable_osense_desc" to "禁用 oplus.osense 云控调度，可恢复",
        "perf_item_vivo_perf_mode" to "开启 vivo 游戏/性能模式",
        "perf_item_vivo_perf_mode_desc" to "写入 vivo_game_mode 与性能模式",
        "perf_item_vivo_disable_power" to "停用 vivo 省电管理",
        "perf_item_vivo_disable_power_desc" to "禁用 com.vivo.pem 电源管理，可恢复",
        "perf_item_vivo_disable_analytics" to "停用 vivo 统计服务",
        "perf_item_vivo_disable_analytics_desc" to "禁用 abe / bgapp / daemonService，可恢复",
        "perf_item_vivo_kill_bg" to "清理 vivo 后台进程",
        "perf_item_vivo_kill_bg_desc" to "am kill-all 清理后台",
        "perf_item_vivo_disable_push" to "关闭 vivo 推送常驻",
        "perf_item_vivo_disable_push_desc" to "关闭 vivo 推送服务常驻后台，可能影响推送到达，可恢复",
        "perf_item_ss_perf_mode" to "开启三星性能模式",
        "perf_item_ss_perf_mode_desc" to "写入 samsung_performance_mode 与游戏加速",
        "perf_item_ss_disable_analytics" to "停用三星统计服务",
        "perf_item_ss_disable_analytics_desc" to "禁用 dqagent / diagmonagent / rubin，可恢复",
        "perf_item_ss_disable_gos" to "停用三星 GOS 降频",
        "perf_item_ss_disable_gos_desc" to "禁用 Game Optimizing Service，游戏不再被强制降频，可恢复",
        "perf_item_ss_max_refresh" to "三星强制 120Hz",
        "perf_item_ss_max_refresh_desc" to "写入 peak/min_refresh_rate 与 refresh_rate_mode",
        "perf_item_ss_kill_bg" to "清理三星后台进程",
        "perf_item_ss_kill_bg_desc" to "am kill-all 清理后台",
        "perf_item_mz_perf_mode" to "开启 Flyme 性能模式",
        "perf_item_mz_perf_mode_desc" to "写入 flyme_performance_mode 与游戏模式",
        "perf_item_mz_disable_analytics" to "停用魅族商店与更新",
        "perf_item_mz_disable_analytics_desc" to "禁用 mstore / flyme.update，可恢复",
        "perf_item_mz_kill_bg" to "清理 Flyme 后台进程",
        "perf_item_mz_kill_bg_desc" to "am kill-all 清理后台",
        "perf_item_generic_perf_mode" to "开启系统性能/游戏模式",
        "perf_item_generic_perf_mode_desc" to "写入通用 game_mode / performance_mode 开关",
        "perf_item_generic_kill_bg_brand" to "清理后台进程",
        "perf_item_generic_kill_bg_brand_desc" to "am kill-all 清理后台",
        "perf_item_generic_disable_analytics" to "停用该品牌统计服务",
        "perf_item_generic_disable_analytics_desc" to "禁用该品牌已知的统计数据上报组件，可恢复",
    )

    private val enStrings = mapOf(
        // General
        "settings" to "Settings",
        "home" to "Home",
        "enabled" to "On",
        "disabled" to "Off",
        "glass_effect" to "Glass Effect",
        "glass_playground" to "Glass Playground",
        "glass_playground_hint" to "Adjust glass effect parameters in real-time",
        "corner_radius" to "Corner Radius",
        "blur_radius" to "Blur Radius",
        "refraction_height" to "Refraction Height",
        "refraction_amount" to "Refraction Amount",
        "chromatic_aberration" to "Chromatic Aberration",
        "vibrancy" to "Vibrancy",
        "global_intensity" to "Global Render Intensity",
        "global_intensity_hint" to "Enhance real-time refraction and blur rendering of all glass effects",
        "long_press_effect" to "Long-Press Glow",
        "long_press_glow_intensity" to "Glow Intensity",
        "long_press_glow_size" to "Glow Size",
        "long_press_refraction" to "Edge Refraction",
        "long_press_glow_hint" to "Long-press the capsule or glass slider to make its edge glow with refraction distortion",
"font_color" to "Text Color",
"color_default" to "Default",
"color_white" to "White",
"color_black" to "Black",
"color_red" to "Red",
"color_orange" to "Orange",
"color_yellow" to "Yellow",
"color_green" to "Green",
"color_cyan" to "Cyan",
"color_blue" to "Blue",
"color_purple" to "Purple",
        "color_pink" to "Pink",
        "color_brown" to "Brown",
        "color_gray" to "Gray",
        "color_dark_red" to "Dark Red",
        "color_dark_orange" to "Dark Orange",
        "color_dark_green" to "Dark Green",
        "color_dark_blue" to "Dark Blue",
        "color_dark_purple" to "Dark Purple",
        "color_light_red" to "Light Red",
        "color_light_orange" to "Light Orange",
        "color_light_yellow" to "Light Yellow",
        "color_light_green" to "Light Green",
        "color_light_blue" to "Light Blue",
        "color_light_purple" to "Light Purple",
        "color_orange_red" to "Orange Red",
        "color_yellow_green" to "Yellow Green",
        "color_teal" to "Teal",
        "color_indigo" to "Indigo",
        "color_magenta" to "Magenta",
        "color_gold" to "Gold",
        "color_silver" to "Silver",
        "color_cream" to "Cream",
        "glass_color" to "Glass Color",
        "save" to "Save Settings",
        "saved" to "✓ Saved",
        "plugins_hint" to "AxManager-style plugins: supports zip packages with scripts, WebUI and system configs",
        "installing" to "Installing...",
        "no_plugins" to "No plugins",
        "no_plugins_hint" to "Click install button to select a zip plugin package",
        "install_plugin" to "Install Plugin",
        "apps" to "Apps",
        "terminal" to "Terminal",
        "back" to "Back",
        "loading" to "Loading...",
        "execute" to "Execute",
        "clear" to "Clear",
        "output" to "Output",
        "adb_toolbox" to "ADB Toolbox",

        // Shizuku
        "shizuku_service" to "Shizuku Service",
        "shizuku_connected" to "Connected - ADB permission available",
        "shizuku_disconnected" to "Disconnected - Some features limited",
        "shizuku_not_connected" to "Shizuku not connected",
        "request_shizuku" to "Request Shizuku Permission",
        "shizuku_permission_granted" to "Shizuku permission granted",
        "shizuku_permission_denied" to "Shizuku permission denied",
        "wireless_debugging_hint" to "Please enable wireless debugging in developer options",
        "authorization_required" to "Authorization required to use this feature",

        // Display settings
        "display_settings" to "Display Settings",
        "dark_mode" to "Dark Mode",
        "light_mode" to "Light Mode",
        "language" to "Language",
        "chinese" to "Chinese",
        "english" to "English",
        "wallpaper" to "Wallpaper",
        "set_wallpaper" to "Set Wallpaper",
        "screen_brightness" to "Screen Brightness",
        "screen_timeout" to "Screen Timeout",

        // System actions
        "system_actions" to "System Actions",
        "reboot" to "Reboot",
        "recovery" to "Recovery",
        "bootloader" to "Bootloader",
        "shutdown" to "Shutdown",
        "restart_systemui" to "Restart SystemUI",
        "screenshot" to "Screenshot",

        // Device info
        "device_info" to "Device Info",
        "model" to "Model",
        "brand" to "Brand",
        "android_version" to "Android Version",
        "sdk" to "SDK",
        "memory" to "Memory",
        "storage" to "Storage",
        "battery" to "Battery",
        "refresh_rate" to "Refresh Rate",
        "root" to "Root",
        "root_obtained" to "Root permission granted",
        "root_not_obtained" to "Root permission not granted",
        "view_details" to "View Details",
        "cpu_info" to "CPU Info",
        "cpu_cores" to "CPU Cores",
        "screen_resolution" to "Screen Resolution",
        "kernel_version" to "Kernel Version",

        // Quick actions
        "quick_actions" to "Quick Actions",
        "adb_panel" to "ADB Panel",
        "permissions" to "Permissions",
        "root_manager" to "Root Manager",
        "shell_executor" to "Shell",
        "app_manager" to "App Manager",

        // ADB Panel
        "adb_quick_panel" to "ADB Quick Panel",
        "device_control" to "Device Control",
        "system_settings" to "System Settings",
        "enable_adb" to "Enable ADB",
        "disable_adb" to "Disable ADB",
        "install_unknown_apps" to "Install Unknown Apps",
        "cleanup_operations" to "Cleanup Operations",
        "clean_all_cache" to "Clean All Cache",
        "clean_logcat" to "Clean Logcat",

        // App manager
        "show_system_apps" to "Show System Apps",
        "system_app" to "System App",
        "user_app" to "User App",
        "type" to "Type",
        "status" to "Status",
        "normal" to "Normal",
        "frozen" to "Frozen",
        "not_frozen" to "Not Frozen",
        "version" to "Version",
        "package_name" to "Package Name",
        "freeze" to "Freeze",
        "unfreeze" to "Unfreeze",
        "uninstall" to "Uninstall",
        "clear_cache" to "Clear Cache",
        "force_stop" to "Force Stop",
        "app_actions" to "App Actions",
        "app_permissions" to "Permissions",
        "app_detail" to "App Detail",

        // Permission manager
        "permission_manager" to "Permission Manager",
        "granted" to "Granted",
        "not_granted" to "Not Granted",
        "grant" to "Grant",
        "revoke" to "Revoke",

        // Root manager
        "root_status" to "Root Status",
        "root_permission" to "Root Permission",
        "su_version" to "Su Version",
        "busybox_version" to "BusyBox Version",
        "request_root" to "Request Root Permission",
        "verify_root" to "Verify Root Permission",
        "root_verified" to "Root permission verified",
        "root_verify_failed" to "Root permission verification failed",
        "root_quick_commands" to "Root Quick Commands",
        "view_uid" to "View UID",
        "mount_rw" to "Mount RW",
        "mount_ro" to "Mount RO",
        "modify_hosts" to "Modify Hosts",
        "clear_data" to "Clear Data",
        "view_processes" to "View Processes",
        "execution_result" to "Execution Result",
        "exit_code" to "Exit Code",
        "error_output" to "Error",

        // Shell/Terminal
        "shell_executor_title" to "Shell Executor",
        "terminal_title" to "Terminal",
        "adb_module" to "ADB Module",
        "adb_plugins" to "ADB Plugins",
        "root_module" to "Root Module",
        "module_hint" to "Select a zip format Magisk/KernelSU module file to flash. Root permission required.",
        "select_module_file" to "Select Module File",
        "choose_file" to "Choose File",
        "no_file_selected" to "No file selected",
        "flash_module" to "Flash Module",
        "module_installing" to "Flashing...",
        "install_log" to "Install Log",
        "plugins" to "Plugins",
        "install_plugin" to "Install",
        "no_plugins" to "No plugins",
        "no_plugins_hint" to "Tap Install to add AxManager-style plugins",
        "author" to "Author",
        "enabled" to "Enabled",
        "disabled" to "Disabled",
        "enable" to "Enable",
        "disable" to "Disable",
        "uninstall" to "Uninstall",
        "run_action" to "Run",
        "action_output" to "Output",
        "actions" to "Actions",
        "flash_mode" to "Flash Mode",
        "adb_mode" to "ADB Mode",
        "root_mode" to "Root Mode",
        "adb_mode_hint" to "Flash via Shizuku/ADB permission, no Root required. Supports Magisk module scripts and APK installation.",
        "root_mode_hint" to "Flash Magisk/KernelSU modules via Root permission. Requires a rooted device with Magisk or KernelSU installed.",
        "adb_terminal_hint" to "ADB Terminal - Enter command to execute",
        "enter_command" to "Enter command...",
        "command_history" to "Command History",
        "clear_screen" to "Clear Screen",
        "diagnose" to "Diagnose",
        "execute_btn" to "Execute",

        // Operation results
        "success" to "Success",
        "failed" to "Failed",
        "operation_failed" to "Operation failed",
        "app_frozen" to "App frozen",
        "app_unfrozen" to "App unfrozen",
        "app_uninstalled" to "App uninstalled",
        "cache_cleared" to "Cache cleared",
        "app_force_stopped" to "App force stopped",
        "permission_granted" to "Permission granted",
        "permission_revoked" to "Permission revoked",
        "brightness_set" to "Brightness set",
        "timeout_set" to "Timeout set",
        "rebooting" to "Rebooting...",
        "wallpaper_set" to "Wallpaper set",

        // Logcat
        "logcat" to "Logcat",
        "clear_logcat_done" to "Logcat cleared",

        // New
        "executing" to "Executing",
        "need_root_or_shizuku" to "Need Root or Shizuku",
        "allowed" to "Allowed",
        "denied" to "Denied",
        "more_items" to "More",
        "hindi" to "हिन्दी",

        // Dynamic Wallpaper
        "dynamic_wallpaper" to "Dynamic Wallpaper",
        "splash_animation" to "Splash Animation",
        "splash_video_hint" to "Use a video as the splash animation, auto-fit to any resolution (2K etc.), frame rate follows the video",
        "splash_select_video" to "Select Splash Video",
        "splash_video_selected" to "Splash video set",
        "splash_current" to "Current splash video",
        "splash_clear" to "Restore default splash",
        "enable_dynamic_wallpaper" to "Enable Dynamic Wallpaper",
        "video_file" to "Video File",
        "select_video" to "Select Video File",
        "video_selected" to "Video Selected, Tap to Change",
        "current_video" to "Current Video:",
        "video_hint" to "Supports MP4, 3GP and other common video formats, loops as app background",
        "delete_video" to "Delete Video",

        // Glass Effect Adjustment
        "home_glass" to "Home Glass",
        "terminal_glass" to "Terminal Glass",
        "settings_glass" to "Settings Glass",
        "apps_glass" to "App Manager Glass",
        "adbmodule_glass" to "ADB Module Glass",
        "plugins_glass" to "Plugins Glass",

        // Nav Capsule Adjustment
        "nav_capsule_settings" to "Nav Capsule Settings",
        "capsule_shape" to "Capsule Shape",
        "round" to "Round",
        "square" to "Square",
        "capsule" to "Capsule",
        "capsule_height" to "Capsule Height",
        "capsule_width" to "Capsule Width",
        "auto" to "Auto",
        "capsule_corner" to "Capsule Corner",
        "capsule_blur" to "Capsule Blur",
        "capsule_opacity" to "Capsule Opacity",

        // Nav Glass
        "nav_glass" to "Navigation Glass",

        "opacity" to "Opacity",

        // Root Tools
        "root_tool" to "One-Click Root Tool",
        "temp_root" to "Temp Root",
        "root_tool_hint" to "Supports Magisk / KernelSU / Temp Root",
        "detecting" to "Detecting...",
        "select_root_method" to "Select Root Method",
        "exec_progress" to "Execution Progress",
        "redetect" to "Re-detect Device",
        "not_supported" to "Not Supported",
        "risk_warning" to "⚠️ Risk Warning",

        // Dhizuku
        "use_dhizuku" to "Use Dhizuku Permission",
        "dhizuku_hint" to "A permission one layer lower than Shizuku, based on Device Owner",
        "dhizuku_notice" to "Note: Before activation, ensure no other accounts on the device (including dual-space)",
        "dhizuku_activate_hint" to "Please activate Dhizuku as device owner via ADB",
        "dhizuku_not_active" to "Dhizuku Not Active",
        "dhizuku_install_hint" to "Please install Dhizuku app first",
        "dhizuku_denied" to "Dhizuku Permission Denied",
        "dhizuku_granted" to "Dhizuku Permission Granted",
        "dhizuku_requesting" to "Requesting...",
        "dhizuku_request" to "Request Dhizuku Permission",
        "dhizuku_not_installed" to "Dhizuku not installed",
        "dhizuku_active" to "Active as Device Owner",
        "dhizuku_inactive" to "Installed but not active",
        "dhizuku_activating" to "Activating Dhizuku...",
        "dhizuku_activate" to "Activate Dhizuku",
        "dhizuku_removing" to "Removing Dhizuku...",
        "dhizuku_remove" to "Remove Dhizuku",

        // Shell Executor
        "use_root" to "Execute with Root",
        "shell_input_hint" to "Enter Shell command...",
        "quick_commands" to "Quick Commands",

        // Root Device Info
        "brand" to "Brand",
        "model" to "Model",
        "device_codename" to "Device Codename",
        "android_version" to "Android Version",
        "kernel_version" to "Kernel Version",
        "bl_status" to "Bootloader",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "gki_device" to "GKI Device",
        "yes" to "Yes",
        "no" to "No",
        "rooted" to "Rooted",
        "temp_root" to "Temp Root",
        "unknown" to "Unknown",
        "supported" to "Supported",
        "temp_root_vuln" to "Temp Root (Exploit)",
        "magisk_desc" to "Patch boot.img, supports module system",
        "kernelsu_desc" to "Kernel-level root, better performance",
        "temproot_desc" to "Exploit-based, lost on reboot, no BL unlock needed",
        "checking_device" to "Detecting device...",
        "extracting_boot" to "Extracting boot.img...",
        "patching_boot" to "Patching boot.img...",
        "flashing_boot" to "Flashing boot.img...",
        "rebooting" to "Rebooting device...",
        "op_success" to "Operation Successful",
        "op_failed" to "Operation Failed",
        "start_root" to "Start Root",
        "executing" to "Executing...",
        "unsupported_msg" to "This device does not support one-click Root. Please ensure:\n1. Bootloader is unlocked\n2. Device supports Magisk or KernelSU\n3. Or use a device that supports temp root",
        "risk_msg" to "1. Root may brick your device, proceed with caution\n2. Rooting voids official warranty\n3. Some banking/payment apps may not work\n4. Back up important data first\n5. Temp root is exploit-based and lost on reboot\n6. Magisk/KernelSU require unlocked Bootloader",
        "ghostlock" to "GhostLock (OnePlus)",
        "temproot_xiaomi" to "TempRoot (Xiaomi)",
        "msg_extract_boot" to "Extracting boot.img...",
        "msg_patch_magisk" to "Patching boot.img with Magisk...",
        "msg_flash_boot" to "Flashing patched boot.img...",
        "msg_temp_root" to "Performing temp root...",
        "msg_check_ksu" to "Checking for KernelSU...",
        "msg_no_ksu" to "KernelSU not detected, opening terminal...",
        "msg_error_prefix" to "Error: ",
        "waiting_cmd" to "Waiting for command...",
        "err_bracket" to "[Error]",
        "exit_code_bracket" to "[Exit code: ",
        "ksu_terminal_banner" to "  KernelSU not detected",
        "ksu_terminal_website" to "KernelSU website: ",
        "ksu_terminal_copy" to "Copy the URL above to browser to download KernelSU",
        "ksu_terminal_open" to "Or open directly with the command below:",
        "ksu_terminal_tried" to "Tried to open browser, if not opened please copy the URL manually",

        // Wallpaper Actions
        "clear_wallpaper" to "Clear Wallpaper",
        "wallpaper_cleared" to "Wallpaper Cleared",
        "performance_boost" to "Performance Boost",
        "performance_boost_hint" to "Brand-adaptive real ADB commands to boost performance in one tap",
        "phone_inspector" to "Phone Inspector",
        "phone_inspector_hint" to "Detect model and ROM, then verify which commands actually work here",
        "not_recognized_brand" to "Unrecognized brand",
        "brand_specific_count" to " brand-specific tweaks",
        "generic_count" to " generic tweaks",
        "run_selected" to "Run selected",
        "run_all" to "Run all",
        "one_tap_boost" to "One-tap boost",
        "select_all" to "Select all",
        "select_none" to "Select none",
        "selected_count" to "%1\$d selected",
        "running_item" to "Running",
        "run_progress" to "Progress %1\$d / %2\$d",
        "boost_done_title" to "Boost complete",
        "boost_success_count" to "%1\$d succeeded",
        "boost_failed_count" to "%2\$d failed",
        "freed_memory" to "Freed %1\$d MB",
        "used_time" to "Took %1\$d ms",
        "hide_details" to "Hide details",
        "requires_root" to "Root required",
        "requires_shizuku" to "Shizuku required",
        "risk_safe" to "Safe",
        "risk_caution" to "Caution",
        "risk_risky" to "High risk",
        "confirm_run_risky" to "This is a high-risk action. Continue?",
        "confirm_run" to "Continue",
        "cancel" to "Cancel",
        "run_failed_reason" to "Failure reason",
        "no_permission_hint" to "Neither Shizuku nor Root is available, some commands cannot take effect",
        "grant_shizuku" to "Grant Shizuku permission",
        "go_to_settings" to "Open settings",
        "execute_fix" to "Apply fix",
        "inspect_running" to "Inspecting",
        "inspect_phase" to "Phase %1\$d / %2\$d",
        "inspect_score" to "Score",
        "inspect_ok_count" to "%1\$d OK",
        "inspect_warn_count" to "%1\$d to optimize",
        "inspect_fail_count" to "%1\$d unsupported",
        "re_inspect" to "Re-inspect",
        "inspect_device_summary" to "Device info",
        "inspect_fix_all" to "Fix all",
        "inspect_all_fixed" to "Submitted %1\$d optimizations",
        "inspect_group_device" to "Device & system",
        "inspect_group_perf" to "Performance settings",
        "inspect_group_brand" to "Brand capabilities",
        "inspect_group_refresh" to "Screen refresh rate",
        "inspect_group_root" to "Root / Shizuku",
        "not_detected" to "Not detected",
        "available" to "Available",
        "configured" to "Configured",
        "not_configured" to "Not configured",
        "unsupported" to "Unsupported",
        "refresh_rate_fix" to "Fix refresh rate",
        "refresh_rate_detail" to "Current %1\$s / Max %2\$s, supported: %3\$s",
        "refresh_rate_supported" to "Supported rates",
        "refresh_rate_reset" to "Reset to auto",
        "refresh_rate_fixed" to "Refresh rate fixed",
        "refresh_rate_confirm" to "Force the display to its highest refresh rate. Battery usage may increase. Continue?",
        "perf_cat_background" to "Background",
        "perf_cat_animation" to "Animation",
        "perf_cat_cpu" to "CPU & scheduler",
        "perf_cat_memory" to "Memory & cache",
        "perf_cat_power" to "Power",
        "perf_cat_network" to "Network",
        "perf_cat_storage" to "Storage",
        "perf_cat_display" to "Display & refresh",
        "perf_cat_brand" to "Brand tuning",
        "brand_generic" to "Generic Android",
        "brand_xiaomi" to "Xiaomi / Redmi / POCO",
        "brand_huawei" to "Huawei",
        "brand_honor" to "HONOR",
        "brand_oppo" to "OPPO",
        "brand_realme" to "realme",
        "brand_vivo" to "vivo",
        "brand_iqoo" to "iQOO",
        "brand_oneplus" to "OnePlus",
        "brand_samsung" to "Samsung",
        "brand_meizu" to "Meizu",
        "brand_nubia" to "Nubia / RedMagic",
        "brand_asus" to "ASUS ROG",
        "brand_sony" to "Sony",
        "brand_motorola" to "Motorola",
        "brand_google" to "Google Pixel",
        "perf_item_kill_bg" to "Kill all background processes",
        "perf_item_kill_bg_desc" to "am kill-all frees every reclaimable background process, no root needed",
        "perf_item_trim_caches" to "Trim all app caches",
        "perf_item_trim_caches_desc" to "pm trim-caches releases cached space of all apps",
        "perf_item_compact_bg" to "Compact background memory",
        "perf_item_compact_bg_desc" to "Compact memory of system processes (Android 12+)",
        "perf_item_drop_caches" to "Drop kernel page cache",
        "perf_item_drop_caches_desc" to "drop_caches=3 frees kernel cache pages, needs root",
        "perf_item_anim_scale_off" to "Speed animations to 0.5x",
        "perf_item_anim_scale_off_desc" to "Window/transition/animator scale set to 0.5x, UI feels snappier, reversible",
        "perf_item_anim_scale_zero" to "Disable animations (0x)",
        "perf_item_anim_scale_zero_desc" to "Turn animations off completely, fastest but visually abrupt, reversible",
        "perf_item_cpu_force_gpu" to "Force GPU rendering",
        "perf_item_cpu_force_gpu_desc" to "Force GPU rendering for the UI to offload the CPU (may flicker on some devices)",
        "perf_item_cpu_disable_low_power" to "Exit battery saver",
        "perf_item_cpu_disable_low_power_desc" to "Disable low power mode and lift CPU throttling",
        "perf_item_cpu_perf_mode" to "CPU governor to performance",
        "perf_item_cpu_perf_mode_desc" to "All cores switch to the performance governor; hot and power hungry, needs root",
        "perf_item_cpu_min_freq_max" to "Pin CPU min frequency to max",
        "perf_item_cpu_min_freq_max_desc" to "Set scaling_min_freq to cpuinfo_max_freq to avoid downclocking, needs root",
        "perf_item_cpu_stop_thermal" to "Stop thermal daemon",
        "perf_item_cpu_stop_thermal_desc" to "Stop vendor thermal throttling; hardware risk, needs root",
        "perf_item_cpu_setenforce_zero" to "SELinux permissive",
        "perf_item_cpu_setenforce_zero_desc" to "setenforce 0 relaxes permission checks; reduces security, needs root",
        "perf_item_mem_disable_zram" to "Disable ZRAM swap",
        "perf_item_mem_disable_zram_desc" to "Disable compressed swap to cut CPU cost; low-RAM devices may kill apps sooner, needs root",
        "perf_item_mem_vfs_pressure" to "Tune kernel memory params",
        "perf_item_mem_vfs_pressure_desc" to "Adjust vfs_cache_pressure and dirty writeback thresholds, needs root",
        "perf_item_mem_lmk_protect" to "Tune low memory killer",
        "perf_item_mem_lmk_protect_desc" to "Relax LMK thresholds so background apps survive longer, needs root",
        "perf_item_power_saver_off" to "Disable battery saver & Doze",
        "perf_item_power_saver_off_desc" to "Turn off battery saver and Doze so background work is not frozen",
        "perf_item_power_unrestrict" to "Unrestrict SystemUI",
        "perf_item_power_unrestrict_desc" to "Whitelist SystemUI from Doze and allow background run to reduce jank",
        "perf_item_power_adb_wifi_off" to "Turn off Wi-Fi and data",
        "perf_item_power_adb_wifi_off_desc" to "svc turns radios off for power saving, reversible",
        "perf_item_net_tcp_fast" to "Optimize TCP buffers",
        "perf_item_net_tcp_fast_desc" to "Enlarge TCP send/receive buffers for better throughput, needs root",
        "perf_item_net_dns_flush" to "Flush DNS cache",
        "perf_item_net_dns_flush_desc" to "Clear the netd resolver cache to fix stale lookups",
        "perf_item_storage_vacuum" to "Vacuum app databases",
        "perf_item_storage_vacuum_desc" to "Run SQLite VACUUM on app databases to shrink and speed them up; needs root and time",
        "perf_item_storage_fstrim" to "Run flash TRIM",
        "perf_item_storage_fstrim_desc" to "fstrim reclaims free flash blocks to restore write speed, needs root",
        "perf_item_storage_drop_logs" to "Clear logs and crash dumps",
        "perf_item_storage_drop_logs_desc" to "Clear logcat plus anr/tombstones to free space",
        "perf_item_display_max_refresh" to "Unlock max refresh rate",
        "perf_item_display_max_refresh_desc" to "Detect the highest supported rate and write peak_refresh_rate, fixing the 60Hz lock",
        "perf_item_display_force_high_refresh" to "Force 120Hz",
        "perf_item_display_force_high_refresh_desc" to "Set peak and min refresh rate to 120Hz; falls back on non-120Hz panels",
        "perf_item_display_aod_off" to "Turn off always-on display",
        "perf_item_display_aod_off_desc" to "Disable AOD to cut idle power, reversible",
        "perf_item_mi_optimization_on" to "Enable MIUI optimization",
        "perf_item_mi_optimization_on_desc" to "Enable mi_optimization and turn off cloud sync auto-sync",
        "perf_item_mi_kill_background" to "Remove background process limit",
        "perf_item_mi_kill_background_desc" to "Set background_process_limit=0 then am kill-all",
        "perf_item_mi_disable_powerkeeper" to "Relax PowerKeeper limits",
        "perf_item_mi_disable_powerkeeper_desc" to "Raise per-core power check caps to reduce PowerKeeper throttling",
        "perf_item_mi_disable_joyose" to "Stop Joyose cloud control",
        "perf_item_mi_disable_joyose_desc" to "Disable com.xiaomi.joyose frequency cloud control for steadier game FPS, reversible",
        "perf_item_mi_disable_analytics" to "Disable Xiaomi ads & analytics",
        "perf_item_mi_disable_analytics_desc" to "Disable analytics / mipicks / msa / metoknlp to cut wakeups, reversible",
        "perf_item_mi_gpu_tuning" to "Enable game turbo",
        "perf_item_mi_gpu_tuning_desc" to "Force skiagl renderer and enable game turbo mode",
        "perf_item_mi_ram_expansion_off" to "Disable memory extension",
        "perf_item_mi_ram_expansion_off_desc" to "Disable ZRAM memory extension, needs root",
        "perf_item_hw_disable_powergenie" to "Stop Huawei PowerGenie",
        "perf_item_hw_disable_powergenie_desc" to "Disable com.huawei.powergenie aggressive power saving, reversible",
        "perf_item_hw_disable_analytics" to "Stop Huawei analytics",
        "perf_item_hw_disable_analytics_desc" to "Disable hwaps / bd / microkernel reporting, reversible",
        "perf_item_hw_perf_mode" to "Enable Huawei performance mode",
        "perf_item_hw_perf_mode_desc" to "Write hw_power_mode=1",
        "perf_item_hw_kill_bg" to "Kill Huawei background processes",
        "perf_item_hw_kill_bg_desc" to "am kill-all clears background work",
        "perf_item_hw_gpu_turbo" to "Enable GPU Turbo",
        "perf_item_hw_gpu_turbo_desc" to "Force GPU rendering and enable the GPU Turbo flag, needs root",
        "perf_item_oppo_perf_mode" to "Enable ColorOS performance mode",
        "perf_item_oppo_perf_mode_desc" to "Write oppo_performance_mode and game mode",
        "perf_item_oppo_disable_power" to "Stop OPPO power guard",
        "perf_item_oppo_disable_power_desc" to "Disable oppoguardelf power guard, reversible",
        "perf_item_oppo_disable_analytics" to "Stop OPPO log services",
        "perf_item_oppo_disable_analytics_desc" to "Disable logkit / usageassist reporting, reversible",
        "perf_item_oppo_kill_bg" to "Kill ColorOS background processes",
        "perf_item_oppo_kill_bg_desc" to "am kill-all clears background work",
        "perf_item_oppo_disable_osense" to "Stop oSense scheduling",
        "perf_item_oppo_disable_osense_desc" to "Disable oplus.osense cloud scheduling, reversible",
        "perf_item_vivo_perf_mode" to "Enable vivo game/performance mode",
        "perf_item_vivo_perf_mode_desc" to "Write vivo_game_mode and performance mode",
        "perf_item_vivo_disable_power" to "Stop vivo power manager",
        "perf_item_vivo_disable_power_desc" to "Disable com.vivo.pem power management, reversible",
        "perf_item_vivo_disable_analytics" to "Stop vivo analytics",
        "perf_item_vivo_disable_analytics_desc" to "Disable abe / bgapp / daemonService, reversible",
        "perf_item_vivo_kill_bg" to "Kill vivo background processes",
        "perf_item_vivo_kill_bg_desc" to "am kill-all clears background work",
        "perf_item_vivo_disable_push" to "Stop vivo push service",
        "perf_item_vivo_disable_push_desc" to "Stop the resident vivo push service; push delivery may be affected, reversible",
        "perf_item_ss_perf_mode" to "Enable Samsung performance mode",
        "perf_item_ss_perf_mode_desc" to "Write samsung_performance_mode and game booster",
        "perf_item_ss_disable_analytics" to "Stop Samsung analytics",
        "perf_item_ss_disable_analytics_desc" to "Disable dqagent / diagmonagent / rubin, reversible",
        "perf_item_ss_disable_gos" to "Disable Samsung GOS throttling",
        "perf_item_ss_disable_gos_desc" to "Disable Game Optimizing Service so games are not throttled, reversible",
        "perf_item_ss_max_refresh" to "Force Samsung 120Hz",
        "perf_item_ss_max_refresh_desc" to "Write peak/min_refresh_rate and refresh_rate_mode",
        "perf_item_ss_kill_bg" to "Kill Samsung background processes",
        "perf_item_ss_kill_bg_desc" to "am kill-all clears background work",
        "perf_item_mz_perf_mode" to "Enable Flyme performance mode",
        "perf_item_mz_perf_mode_desc" to "Write flyme_performance_mode and game mode",
        "perf_item_mz_disable_analytics" to "Stop Meizu store & updater",
        "perf_item_mz_disable_analytics_desc" to "Disable mstore / flyme.update, reversible",
        "perf_item_mz_kill_bg" to "Kill Flyme background processes",
        "perf_item_mz_kill_bg_desc" to "am kill-all clears background work",
        "perf_item_generic_perf_mode" to "Enable system performance / game mode",
        "perf_item_generic_perf_mode_desc" to "Write the generic game_mode / performance_mode switches",
        "perf_item_generic_kill_bg_brand" to "Kill background processes",
        "perf_item_generic_kill_bg_brand_desc" to "am kill-all clears background work",
        "perf_item_generic_disable_analytics" to "Stop this brand's analytics",
        "perf_item_generic_disable_analytics_desc" to "Disable known telemetry components of this brand, reversible",
    )
    private val hiStrings = mapOf(
        // सामान्य
        "settings" to "सेटिंग्स",
        "home" to "होम",
        "enabled" to "चालू",
        "disabled" to "बंद",
        "glass_effect" to "लिक्विड ग्लास",
        "glass_playground" to "ग्लास इफ़ेक्ट एडजस्ट",
        "corner_radius" to "कॉर्नर रेडियस",
        "blur_radius" to "ब्लर रेडियस",
        "refraction_height" to "रिफ्रैक्शन हाइट",
        "refraction_amount" to "रिफ्रैक्शन अमाउंट",
        "chromatic_aberration" to "क्रोमैटिक एबरेशन",
        "vibrancy" to "वाइब्रेंसी",
        "global_intensity" to "ग्लोबल रेंडर तीव्रता",
        "global_intensity_hint" to "सभी ग्लास इफ़ेक्ट्स की रीयल-टाइम रिफ्रैक्शन और ब्लर रेंडरिंग बढ़ाएं",
        "long_press_effect" to "लॉन्ग-प्रेस ग्लो",
        "long_press_glow_intensity" to "ग्लो तीव्रता",
        "long_press_glow_size" to "ग्लो साइज़",
        "long_press_refraction" to "एज रिफ्रैक्शन",
        "long_press_glow_hint" to "कैप्सूल या ग्लास स्लाइडर को लंबा दबाएं, किनारा चमकेगा और रिफ्रैक्शन विकृति दिखेगी",
"font_color" to "फ़ॉन्ट रंग",
"color_default" to "डिफ़ॉल्ट",
"color_white" to "सफ़ेद",
"color_black" to "काला",
"color_red" to "लाल",
"color_orange" to "नारंगी",
"color_yellow" to "पीला",
"color_green" to "हरा",
"color_cyan" to "सियान",
"color_blue" to "नीला",
"color_purple" to "बैंगनी",
        "color_pink" to "गुलाबी",
        "color_brown" to "भूरा",
        "color_gray" to "ग्रे",
        "color_dark_red" to "गहरा लाल",
        "color_dark_orange" to "गहरा नारंगी",
        "color_dark_green" to "गहरा हरा",
        "color_dark_blue" to "गहरा नीला",
        "color_dark_purple" to "गहरा बैंगनी",
        "color_light_red" to "हल्का लाल",
        "color_light_orange" to "हल्का नारंगी",
        "color_light_yellow" to "हल्का पीला",
        "color_light_green" to "हल्का हरा",
        "color_light_blue" to "हल्का नीला",
        "color_light_purple" to "हल्का बैंगनी",
        "color_orange_red" to "नारंगी लाल",
        "color_yellow_green" to "पीला हरा",
        "color_teal" to "सियाही",
        "color_indigo" to "इंडिगो",
        "color_magenta" to "मैजेंटा",
        "color_gold" to "सोना",
        "color_silver" to "चांदी",
        "color_cream" to "क्रीम",
        "glass_color" to "ग्लास कलर",
        "save" to "सेव",
        "saved" to "✓ सेव हो गया",
        "apps" to "ऐप्स",
        "terminal" to "टर्मिनल",
        "back" to "वापस",
        "loading" to "लोड हो रहा है...",
        "execute" to "एक्ज़ीक्यूट",
        "clear" to "क्लियर",
        "output" to "आउटपुट",
        "adb_toolbox" to "ADB टूलबॉक्स",
        "plugins" to "प्लगइन्स",
        "install_plugin" to "प्लगइन इंस्टॉल",
        "no_plugins" to "कोई प्लगइन नहीं",
        "author" to "लेखक",
        "enable" to "चालू करें",
        "disable" to "बंद करें",
        "uninstall" to "अनइंस्टॉल",
        "run_action" to "रन",
        "adb_module" to "ADB मॉड्यूल",
        "adb_plugins" to "ADB प्लगइन",
        "root_module" to "रूट मॉड्यूल",
        "select_module_file" to "मॉड्यूल फ़ाइल चुनें",
        "choose_file" to "फ़ाइल चुनें",
        "no_file_selected" to "कोई फ़ाइल नहीं चुनी गई",
        "flash_module" to "मॉड्यूल फ़्लैश करें",
        "module_installing" to "इंस्टॉल हो रहा है...",
        "install_log" to "इंस्टॉल लॉग",
        "success" to "सफल",
        "failed" to "विफल",
        "version" to "वर्ज़न",
        "type" to "प्रकार",
        "status" to "स्थिति",
        "normal" to "सामान्य",
        "frozen" to "फ्रीज़",
        "not_frozen" to "नहीं फ्रीज़",
        "system_app" to "सिस्टम ऐप",
        "user_app" to "यूज़र ऐप",
        "freeze" to "फ्रीज़",
        "unfreeze" to "अनफ्रीज़",
        "clear_cache" to "कैश क्लियर",
        "force_stop" to "फ़ोर्स स्टॉप",
        "app_actions" to "ऐप एक्शन",
        "app_detail" to "ऐप डिटेल",
        "permissions" to "परमिशन",
        "version" to "वर्ज़न",
        "package_name" to "पैकेज नाम",
        "granted" to "दी गई",
        "not_granted" to "नहीं दी गई",
        "grant" to "दें",
        "revoke" to "वापस लें",
        "allowed" to "अनुमति",
        "denied" to "अस्वीकृत",
        "executing" to "चल रहा है",
        "need_root_or_shizuku" to "Root या Shizuku चाहिए",
        "more_items" to "और",
        "dark_mode" to "डार्क मोड",
        "light_mode" to "लाइट मोड",
        "language" to "भाषा",
        "chinese" to "चीनी",
        "english" to "English",
        "hindi" to "हिन्दी",
        "wallpaper" to "वॉलपेपर",
        "set_wallpaper" to "वॉलपेपर सेट करें",
        "reboot" to "रीबूट",
        "shutdown" to "शटडाउन",
        "screenshot" to "स्क्रीनशॉट",
        "device_info" to "डिवाइस जानकारी",
        "model" to "मॉडल",
        "brand" to "ब्रांड",
        "android_version" to "Android वर्ज़न",
        "sdk" to "SDK",
        "refresh_rate" to "रिफ्रेश दर",
        "root" to "Root",
        "memory" to "मेमोरी",
        "storage" to "स्टोरेज",
        "battery" to "बैटरी",
        "root_obtained" to "रूट अनुमति दी गई",
        "root_not_obtained" to "रूट अनुमति नहीं दी गई",
        "show_system_apps" to "सिस्टम ऐप्स दिखाएं",
        "permission_manager" to "परमिशन मैनेजर",
        "app_manager" to "ऐप मैनेजर",
        "app_permissions" to "ऐप परमिशन",
        "quick_actions" to "क्विक एक्शन",
        "adb_panel" to "ADB पैनल",
        "root_manager" to "Root मैनेजर",
        "shell_executor" to "Shell एक्ज़ीक्यूटर",
        "clean_all_cache" to "सभी कैश क्लियर",
        "adb_quick_panel" to "ADB क्विक पैनल",
        "device_control" to "डिवाइस कंट्रोल",
        "system_settings" to "सिस्टम सेटिंग्स",
        "enable_adb" to "ADB चालू",
        "disable_adb" to "ADB बंद",
        "shizuku_service" to "Shizuku सेवा",
        "shizuku_connected" to "कनेक्टेड - ADB परमिशन उपलब्ध",
        "shizuku_disconnected" to "डिस्कनेक्टेड - कुछ फ़ीचर सीमित",
        "shizuku_not_connected" to "Shizuku कनेक्ट नहीं है",
        "request_shizuku" to "Shizuku परमिशन मांगें",
        "shizuku_permission_granted" to "Shizuku परमिशन मिल गई",
        "shizuku_permission_denied" to "Shizuku परमिशन अस्वीकृत",
        "wireless_debugging_hint" to "कृपया डेवलपर ऑप्शन में वायरलेस डीबगिंग चालू करें",
        "authorization_required" to "इस फ़ीचर के लिए अधिकृति चाहिए",
        "display_settings" to "डिस्प्ले सेटिंग्स",
        "screen_brightness" to "स्क्रीन ब्राइटनेस",
        "screen_timeout" to "स्क्रीन टाइमआउट",
        "system_actions" to "सिस्टम एक्शन",
        "recovery" to "Recovery",
        "bootloader" to "Bootloader",
        "restart_systemui" to "SystemUI रीस्टार्ट",
        "cleanup_operations" to "क्लीनअप ऑपरेशन",
        "clean_logcat" to "Logcat क्लियर",
        "logcat" to "Logcat",
        "clear_logcat_done" to "Logcat क्लियर हो गया",
        "root_status" to "Root स्थिति",
        "root_permission" to "Root परमिशन",
        "su_version" to "Su वर्ज़न",
        "busybox_version" to "BusyBox वर्ज़न",
        "request_root" to "Root परमिशन मांगें",
        "verify_root" to "Root परमिशन वेरिफाई",
        "root_verified" to "Root परमिशन वेरिफाई हो गई",
        "root_verify_failed" to "Root परमिशन वेरिफाई विफल",
        "root_quick_commands" to "Root क्विक कमांड",
        "view_uid" to "UID देखें",
        "mount_rw" to "माउंट RW",
        "mount_ro" to "माउंट RO",
        "modify_hosts" to "Hosts मॉडिफाई",
        "clear_data" to "डेटा क्लियर",
        "view_processes" to "प्रोसेस देखें",
        "execution_result" to "एक्ज़ीक्यूशन रिज़ल्ट",
        "exit_code" to "एग्ज़िट कोड",
        "error_output" to "एरर",
        "shell_executor_title" to "Shell एक्ज़ीक्यूटर",
        "terminal_title" to "टर्मिनल",
        "module_hint" to "फ़्लैश करने के लिए zip फ़ॉर्मैट Magisk/KernelSU मॉड्यूल फ़ाइल चुनें। Root परमिशन चाहिए।",
        "adb_mode" to "ADB मोड",
        "root_mode" to "Root मोड",
        "flash_mode" to "फ़्लैश मोड",
        "adb_mode_hint" to "फ़्लैश करने के लिए Shizuku/ADB परमिशन उपयोग करें, Root की ज़रूरत नहीं। Magisk मॉड्यूल स्क्रिप्ट और APK इंस्टॉलेशन सपोर्टेड।",
        "root_mode_hint" to "Magisk/KernelSU मॉड्यूल फ़्लैश करने के लिए Root परमिशन उपयोग करें। डिवाइस Root होना चाहिए और Magisk या KernelSU इंस्टॉल होना चाहिए।",
        "adb_terminal_hint" to "ADB टर्मिनल - कमांड डालें और चलाएं",
        "enter_command" to "कमांड डालें...",
        "command_history" to "कमांड हिस्ट्री",
        "clear_screen" to "स्क्रीन क्लियर",
        "diagnose" to "डायग्नोस",
        "execute_btn" to "एक्ज़ीक्यूट",
        "operation_failed" to "ऑपरेशन विफल",
        "app_frozen" to "ऐप फ्रीज़ हो गया",
        "app_unfrozen" to "ऐप अनफ्रीज़ हो गया",
        "app_uninstalled" to "ऐप अनइंस्टॉल हो गया",
        "cache_cleared" to "कैश क्लियर हो गया",
        "app_force_stopped" to "ऐप फ़ोर्स स्टॉप हो गया",
        "permission_granted" to "परमिशन मिल गई",
        "permission_revoked" to "परमिशन वापस ली गई",
        "brightness_set" to "ब्राइटनेस सेट हो गई",
        "timeout_set" to "टाइमआउट सेट हो गया",
        "rebooting" to "रीबूट हो रहा है...",
        "wallpaper_set" to "वॉलपेपर सेट हो गया",
        "plugins_hint" to "AxManager स्टाइल प्लगइन: zip प्लगइन पैक सपोर्टेड, स्क्रिप्ट, WebUI और सिस्टम कॉन्फ़िग शामिल हो सकते हैं",
        "installing" to "इंस्टॉल हो रहा है...",
        "no_plugins_hint" to "zip प्लगइन पैक चुनने के लिए ऊपर दाएं कोने में इंस्टॉल बटन दबाएं",
        "enabled" to "चालू",
        "disabled" to "बंद",
        "actions" to "एक्शन",
        "action_output" to "रन आउटपुट",
        "view_details" to "डिटेल देखें",
        "cpu_info" to "CPU जानकारी",
        "cpu_cores" to "CPU कोर",
        "screen_resolution" to "स्क्रीन रिज़ॉल्यूशन",
        "kernel_version" to "कर्नल वर्ज़न",
        "install_unknown_apps" to "अनजान ऐप्स इंस्टॉल",
        "glass_playground_hint" to "लिक्विड ग्लास इफ़ेक्ट पैरामीटर रीयल-टाइम एडजस्ट करें",

        // Dynamic Wallpaper
        "dynamic_wallpaper" to "डायनेमिक वॉलपेपर",
        "splash_animation" to "स्प्लैश एनीमेशन",
        "splash_video_hint" to "वीडियो को स्प्लैश एनीमेशन के रूप में उपयोग करें, किसी भी रिज़ॉल्यूशन (2K आदि) में ऑटो-फ़िट, फ्रेम रेट वीडियो का अनुसरण करता है",
        "splash_select_video" to "स्प्लैश वीडियो चुनें",
        "splash_video_selected" to "स्प्लैश वीडियो सेट",
        "splash_current" to "वर्तमान स्प्लैश वीडियो",
        "splash_clear" to "डिफ़ॉल्ट स्प्लैश पुनर्स्थापित करें",
        "enable_dynamic_wallpaper" to "डायनेमिक वॉलपेपर चालू करें",
        "video_file" to "वीडियो फ़ाइल",
        "select_video" to "वीडियो फ़ाइल चुनें",
        "video_selected" to "वीडियो चुना गया, बदलने के लिए टैप करें",
        "current_video" to "वर्तमान वीडियो:",
        "video_hint" to "MP4, 3GP और अन्य सामान्य वीडियो फ़ॉर्मेट समर्थित, ऐप बैकग्राउंड के रूप में लूप होता है",
        "delete_video" to "वीडियो हटाएं",

        // Glass Effect Adjustment
        "home_glass" to "होम ग्लास",
        "terminal_glass" to "टर्मिनल ग्लास",
        "settings_glass" to "सेटिंग्स ग्लास",
        "apps_glass" to "ऐप मैनेजर ग्लास",
        "adbmodule_glass" to "ADB मॉड्यूल ग्लास",
        "plugins_glass" to "प्लगइन ग्लास",

        // Nav Capsule Adjustment
        "nav_capsule_settings" to "नेव कैप्सूल सेटिंग्स",
        "capsule_shape" to "कैप्सूल शेप",
        "round" to "गोल",
        "square" to "वर्ग",
        "capsule" to "कैप्सूल",
        "capsule_height" to "कैप्सूल ऊंचाई",
        "capsule_width" to "कैप्सूल चौड़ाई",
        "auto" to "ऑटो",
        "capsule_corner" to "कैप्सूल कॉर्नर",
        "capsule_blur" to "कैप्सूल ब्लर",
        "capsule_opacity" to "कैप्सूल ओपैसिटी",

        // Nav Glass
        "nav_glass" to "नेविगेशन ग्लास",

        "opacity" to "ओपैसिटी",

        // Root Tools
        "root_tool" to "वन-क्लिक रूट टूल",
        "temp_root" to "अस्थायी रूट",
        "root_tool_hint" to "Magisk / KernelSU / टेम्प रूट सपोर्ट",
        "detecting" to "जांच हो रही है...",
        "select_root_method" to "रूट विधि चुनें",
        "exec_progress" to "प्रगति निष्पादित करें",
        "redetect" to "डिवाइस दोबारा जांचें",
        "not_supported" to "समर्थित नहीं",
        "risk_warning" to "⚠️ जोखिम चेतावनी",

        // Dhizuku
        "use_dhizuku" to "Dhizuku अनुमति का उपयोग करें",
        "dhizuku_hint" to "Shizuku से एक स्तर नीचे की अनुमति, डिवाइस ओनर पर आधारित",
        "dhizuku_notice" to "नोट: सक्रिय करने से पहले सुनिश्चित करें कि डिवाइस पर कोई अन्य खाता नहीं है (डुअल-स्पेस सहित)",
        "dhizuku_activate_hint" to "कृपया ADB के माध्यम से Dhizuku को डिवाइस मालिक के रूप में सक्रिय करें",
        "dhizuku_not_active" to "Dhizuku सक्रिय नहीं है",
        "dhizuku_install_hint" to "कृपया पहले Dhizuku ऐप इंस्टॉल करें",
        "dhizuku_denied" to "Dhizuku अनुमति अस्वीकृत",
        "dhizuku_granted" to "Dhizuku अनुमति प्रदान की गई",
        "dhizuku_requesting" to "अनुरोध हो रहा है...",
        "dhizuku_request" to "Dhizuku अनुमति अनुरोध करें",
        "dhizuku_not_installed" to "Dhizuku इंस्टॉल नहीं है",
        "dhizuku_active" to "डिवाइस ओनर के रूप में सक्रिय",
        "dhizuku_inactive" to "इंस्टॉल है लेकिन सक्रिय नहीं",
        "dhizuku_activating" to "Dhizuku सक्रिय हो रहा है...",
        "dhizuku_activate" to "Dhizuku सक्रिय करें",
        "dhizuku_removing" to "Dhizuku हटाया जा रहा है...",
        "dhizuku_remove" to "Dhizuku हटाएं",

        // Shell Executor
        "use_root" to "रूट के साथ चलाएं",
        "shell_input_hint" to "शेल कमांड दर्ज करें...",
        "quick_commands" to "क्विक कमांड",

        // Root Device Info
        "brand" to "ब्रांड",
        "model" to "मॉडल",
        "device_codename" to "डिवाइस कोडनेम",
        "android_version" to "एंड्रॉइड वर्ज़न",
        "kernel_version" to "कर्नल वर्ज़न",
        "bl_status" to "बूटलोडर",
        "unlocked" to "अनलॉक किया गया",
        "locked" to "लॉक किया गया",
        "gki_device" to "GKI डिवाइस",
        "yes" to "हाँ",
        "no" to "नहीं",
        "rooted" to "रूटेड",
        "temp_root" to "टेम्प रूट",
        "unknown" to "अज्ञात",
        "supported" to "समर्थित",
        "temp_root_vuln" to "टेम्प रूट (एक्सप्लॉइट)",
        "magisk_desc" to "boot.img पैच करें, मॉड्यूल सिस्टम सपोर्ट",
        "kernelsu_desc" to "कर्नल-लेवल रूट, बेहतर प्रदर्शन",
        "temproot_desc" to "एक्सप्लॉइट-आधारित, रिबूट पर खो जाता है, BL अनलॉक की ज़रूरत नहीं",
        "checking_device" to "डिवाइस जांच हो रही है...",
        "extracting_boot" to "boot.img निकाला जा रहा है...",
        "patching_boot" to "boot.img पैच हो रहा है...",
        "flashing_boot" to "boot.img फ़्लैश हो रहा है...",
        "rebooting" to "डिवाइस रीबूट हो रहा है...",
        "op_success" to "ऑपरेशन सफल",
        "op_failed" to "ऑपरेशन विफल",
        "start_root" to "रूट शुरू करें",
        "executing" to "निष्पादित हो रहा है...",
        "unsupported_msg" to "यह डिवाइस वन-क्लिक रूट सपोर्ट नहीं करता। सुनिश्चित करें:\n1. बूटलोडर अनलॉक है\n2. डिवाइस Magisk या KernelSU सपोर्ट करता है\n3. या टेम्प रूट सपोर्ट करने वाला डिवाइस इस्तेमाल करें",
        "risk_msg" to "1. रूट से डिवाइस ब्रिक हो सकती है, सावधानी से आगे बढ़ें\n2. रूट करने से आधिकारिक वारंटी खत्म हो जाती है\n3. कुछ बैंकिंग/पेमेंट ऐप्स काम नहीं कर सकते\n4. पहले महत्वपूर्ण डेटा का बैकअप लें\n5. टेम्प रूट एक्सप्लॉइट-आधारित है, रिबूट पर खो जाता है\n6. Magisk/KernelSU के लिए अनलॉक बूटलोडर चाहिए",
        "ghostlock" to "GhostLock (वनप्लस)",
        "temproot_xiaomi" to "TempRoot (श्याओमी)",
        "msg_extract_boot" to "boot.img निकाला जा रहा है...",
        "msg_patch_magisk" to "Magisk से boot.img पैच हो रहा है...",
        "msg_flash_boot" to "पैच किया हुआ boot.img फ़्लैश हो रहा है...",
        "msg_temp_root" to "टेम्प रूट किया जा रहा है...",
        "msg_check_ksu" to "KernelSU की जांच हो रही है...",
        "msg_no_ksu" to "KernelSU नहीं मिला, टर्मिनल खोला जा रहा है...",
        "msg_error_prefix" to "त्रुटि: ",
        "waiting_cmd" to "कमांड का इंतज़ार है...",
        "err_bracket" to "[त्रुटि]",
        "exit_code_bracket" to "[एग्ज़िट कोड: ",
        "ksu_terminal_banner" to "  KernelSU नहीं मिला",
        "ksu_terminal_website" to "KernelSU वेबसाइट: ",
        "ksu_terminal_copy" to "KernelSU डाउनलोड करने के लिए ऊपर का URL ब्राउज़र में कॉपी करें",
        "ksu_terminal_open" to "या नीचे दिए कमांड से सीधे खोलें:",
        "ksu_terminal_tried" to "ब्राउज़र खोलने का प्रयास किया, नहीं खुला तो URL मैन्युअली कॉपी करें",

        // Wallpaper Actions
        "clear_wallpaper" to "वॉलपेपर हटाएं",
        "wallpaper_cleared" to "वॉलपेपर हटा दिया गया",
        "performance_boost" to "प्रदर्शन बूस्ट",
        "performance_boost_hint" to "ब्रांड के अनुसार असली ADB कमांड से एक टैप में प्रदर्शन बढ़ाएँ",
        "phone_inspector" to "फ़ोन जाँच",
        "phone_inspector_hint" to "मॉडल और ROM पहचानें और जाँचें कि कौन से कमांड वाकई काम करते हैं",
        "not_recognized_brand" to "अपरिचित ब्रांड",
        "brand_specific_count" to " ब्रांड-विशिष्ट ट्वीक",
        "generic_count" to " सामान्य ट्वीक",
        "run_selected" to "चयनित चलाएँ",
        "run_all" to "सभी चलाएँ",
        "one_tap_boost" to "एक टैप बूस्ट",
        "select_all" to "सभी चुनें",
        "select_none" to "कुछ नहीं",
        "selected_count" to "%1\$d चयनित",
        "running_item" to "चल रहा है",
        "run_progress" to "प्रगति %1\$d / %2\$d",
        "boost_done_title" to "बूस्ट पूरा",
        "boost_success_count" to "%1\$d सफल",
        "boost_failed_count" to "%2\$d विफल",
        "freed_memory" to "%1\$d MB मुक्त",
        "used_time" to "%1\$d ms लगे",
        "hide_details" to "विवरण छिपाएँ",
        "requires_root" to "Root आवश्यक",
        "requires_shizuku" to "Shizuku आवश्यक",
        "risk_safe" to "सुरक्षित",
        "risk_caution" to "सावधानी",
        "risk_risky" to "उच्च जोखिम",
        "confirm_run_risky" to "यह उच्च जोखिम वाली क्रिया है। जारी रखें?",
        "confirm_run" to "जारी रखें",
        "cancel" to "रद्द करें",
        "run_failed_reason" to "विफलता का कारण",
        "no_permission_hint" to "Shizuku या Root उपलब्ध नहीं, कुछ कमांड काम नहीं करेंगे",
        "grant_shizuku" to "Shizuku अनुमति दें",
        "go_to_settings" to "सेटिंग्स खोलें",
        "execute_fix" to "सुधार लागू करें",
        "inspect_running" to "जाँच हो रही है",
        "inspect_phase" to "चरण %1\$d / %2\$d",
        "inspect_score" to "स्कोर",
        "inspect_ok_count" to "%1\$d ठीक",
        "inspect_warn_count" to "%1\$d सुधार योग्य",
        "inspect_fail_count" to "%1\$d असमर्थित",
        "re_inspect" to "फिर जाँचें",
        "inspect_device_summary" to "डिवाइस जानकारी",
        "inspect_fix_all" to "सभी ठीक करें",
        "inspect_all_fixed" to "%1\$d सुधार भेजे गए",
        "inspect_group_device" to "डिवाइस और सिस्टम",
        "inspect_group_perf" to "प्रदर्शन सेटिंग्स",
        "inspect_group_brand" to "ब्रांड क्षमताएँ",
        "inspect_group_refresh" to "स्क्रीन रिफ्रेश रेट",
        "inspect_group_root" to "Root / Shizuku",
        "not_detected" to "नहीं मिला",
        "available" to "उपलब्ध",
        "configured" to "कॉन्फ़िगर",
        "not_configured" to "कॉन्फ़िगर नहीं",
        "unsupported" to "असमर्थित",
        "refresh_rate_fix" to "रिफ्रेश रेट ठीक करें",
        "refresh_rate_detail" to "वर्तमान %1\$s / अधिकतम %2\$s, समर्थित: %3\$s",
        "refresh_rate_supported" to "समर्थित दरें",
        "refresh_rate_reset" to "ऑटो पर रीसेट",
        "refresh_rate_fixed" to "रिफ्रेश रेट ठीक हो गया",
        "refresh_rate_confirm" to "डिस्प्ले को उच्चतम रिफ्रेश रेट पर बाध्य करें। बैटरी खपत बढ़ सकती है। जारी रखें?",
        "perf_cat_background" to "बैकग्राउंड",
        "perf_cat_animation" to "एनिमेशन",
        "perf_cat_cpu" to "CPU और शेड्यूलर",
        "perf_cat_memory" to "मेमोरी और कैश",
        "perf_cat_power" to "पावर",
        "perf_cat_network" to "नेटवर्क",
        "perf_cat_storage" to "स्टोरेज",
        "perf_cat_display" to "डिस्प्ले और रिफ्रेश",
        "perf_cat_brand" to "ब्रांड ट्यूनिंग",
        "brand_generic" to "सामान्य Android",
        "brand_xiaomi" to "Xiaomi / Redmi / POCO",
        "brand_huawei" to "Huawei",
        "brand_honor" to "HONOR",
        "brand_oppo" to "OPPO",
        "brand_realme" to "realme",
        "brand_vivo" to "vivo",
        "brand_iqoo" to "iQOO",
        "brand_oneplus" to "OnePlus",
        "brand_samsung" to "Samsung",
        "brand_meizu" to "Meizu",
        "brand_nubia" to "Nubia / RedMagic",
        "brand_asus" to "ASUS ROG",
        "brand_sony" to "Sony",
        "brand_motorola" to "Motorola",
        "brand_google" to "Google Pixel",
        "perf_item_kill_bg" to "सभी बैकग्राउंड प्रक्रियाएँ बंद करें",
        "perf_item_kill_bg_desc" to "am kill-all से सभी रिक्लेम करने योग्य बैकग्राउंड प्रक्रियाएँ मुक्त, root की ज़रूरत नहीं",
        "perf_item_trim_caches" to "सभी ऐप कैश साफ़ करें",
        "perf_item_trim_caches_desc" to "pm trim-caches सभी ऐप्स का कैश मुक्त करता है",
        "perf_item_compact_bg" to "बैकग्राउंड मेमोरी कॉम्पैक्ट करें",
        "perf_item_compact_bg_desc" to "सिस्टम प्रक्रियाओं की मेमोरी कॉम्पैक्ट करें (Android 12+)",
        "perf_item_drop_caches" to "कर्नेल पेज कैश हटाएँ",
        "perf_item_drop_caches_desc" to "drop_caches=3 कर्नेल कैश मुक्त करता है, root चाहिए",
        "perf_item_anim_scale_off" to "एनिमेशन 0.5x करें",
        "perf_item_anim_scale_off_desc" to "विंडो/ट्रांज़िशन/एनिमेटर 0.5x, UI तेज़ लगता है, वापसी संभव",
        "perf_item_anim_scale_zero" to "एनिमेशन बंद करें (0x)",
        "perf_item_anim_scale_zero_desc" to "एनिमेशन पूरी तरह बंद, सबसे तेज़ पर दिखने में कठोर, वापसी संभव",
        "perf_item_cpu_force_gpu" to "GPU रेंडरिंग बाध्य करें",
        "perf_item_cpu_force_gpu_desc" to "UI के लिए GPU रेंडरिंग बाध्य करें (कुछ डिवाइस पर झिलमिलाहट)",
        "perf_item_cpu_disable_low_power" to "बैटरी सेवर बंद करें",
        "perf_item_cpu_disable_low_power_desc" to "लो पावर मोड बंद कर CPU थ्रॉटलिंग हटाएँ",
        "perf_item_cpu_perf_mode" to "CPU गवर्नर performance",
        "perf_item_cpu_perf_mode_desc" to "सभी कोर performance गवर्नर पर; गर्मी और बैटरी खपत, root चाहिए",
        "perf_item_cpu_min_freq_max" to "CPU न्यूनतम फ्रीक्वेंसी अधिकतम पर",
        "perf_item_cpu_min_freq_max_desc" to "scaling_min_freq को cpuinfo_max_freq पर सेट करें, root चाहिए",
        "perf_item_cpu_stop_thermal" to "थर्मल डेमॉन रोकें",
        "perf_item_cpu_stop_thermal_desc" to "वेंडर थर्मल थ्रॉटलिंग रोकें; हार्डवेयर जोखिम, root चाहिए",
        "perf_item_cpu_setenforce_zero" to "SELinux permissive",
        "perf_item_cpu_setenforce_zero_desc" to "setenforce 0 से अनुमति जाँच ढीली; सुरक्षा घटती है, root चाहिए",
        "perf_item_mem_disable_zram" to "ZRAM स्वैप बंद करें",
        "perf_item_mem_disable_zram_desc" to "कंप्रेस्ड स्वैप बंद कर CPU बचाएँ; कम RAM डिवाइस पर ऐप जल्दी बंद हो सकते हैं, root चाहिए",
        "perf_item_mem_vfs_pressure" to "कर्नेल मेमोरी पैरामीटर ट्यून करें",
        "perf_item_mem_vfs_pressure_desc" to "vfs_cache_pressure और डर्टी राइटबैक थ्रेशोल्ड बदलें, root चाहिए",
        "perf_item_mem_lmk_protect" to "लो मेमोरी किलर ट्यून करें",
        "perf_item_mem_lmk_protect_desc" to "LMK थ्रेशोल्ड ढीले करें ताकि बैकग्राउंड ऐप बचे रहें, root चाहिए",
        "perf_item_power_saver_off" to "बैटरी सेवर और Doze बंद करें",
        "perf_item_power_saver_off_desc" to "बैटरी सेवर और Doze बंद करें ताकि बैकग्राउंड फ्रीज़ न हो",
        "perf_item_power_unrestrict" to "SystemUI प्रतिबंध हटाएँ",
        "perf_item_power_unrestrict_desc" to "SystemUI को Doze व्हाइटलिस्ट में डालें ताकि रुकावट कम हो",
        "perf_item_power_adb_wifi_off" to "Wi-Fi और डेटा बंद करें",
        "perf_item_power_adb_wifi_off_desc" to "svc से रेडियो बंद कर बिजली बचाएँ, वापसी संभव",
        "perf_item_net_tcp_fast" to "TCP बफ़र अनुकूलित करें",
        "perf_item_net_tcp_fast_desc" to "TCP सेंड/रिसीव बफ़र बड़े करें, root चाहिए",
        "perf_item_net_dns_flush" to "DNS कैश फ्लश करें",
        "perf_item_net_dns_flush_desc" to "netd resolver कैश साफ़ करें",
        "perf_item_storage_vacuum" to "ऐप डेटाबेस वैक्यूम करें",
        "perf_item_storage_vacuum_desc" to "ऐप डेटाबेस पर SQLite VACUUM चलाएँ; root और समय चाहिए",
        "perf_item_storage_fstrim" to "फ्लैश TRIM चलाएँ",
        "perf_item_storage_fstrim_desc" to "fstrim से फ्लैश ब्लॉक रिक्लेम करें, root चाहिए",
        "perf_item_storage_drop_logs" to "लॉग और क्रैश डंप साफ़ करें",
        "perf_item_storage_drop_logs_desc" to "logcat और anr/tombstones साफ़ करें",
        "perf_item_display_max_refresh" to "अधिकतम रिफ्रेश रेट अनलॉक करें",
        "perf_item_display_max_refresh_desc" to "सर्वोच्च समर्थित दर पढ़कर peak_refresh_rate लिखें, 60Hz लॉक ठीक करें",
        "perf_item_display_force_high_refresh" to "120Hz बाध्य करें",
        "perf_item_display_force_high_refresh_desc" to "peak और min रिफ्रेश रेट 120Hz; 120Hz स्क्रीन न हो तो फ़ॉलबैक",
        "perf_item_display_aod_off" to "ऑलवेज़-ऑन डिस्प्ले बंद करें",
        "perf_item_display_aod_off_desc" to "AOD बंद कर आइडल खपत घटाएँ, वापसी संभव",
        "perf_item_mi_optimization_on" to "MIUI ऑप्टिमाइज़ेशन चालू करें",
        "perf_item_mi_optimization_on_desc" to "mi_optimization चालू करें और क्लाउड सिंक बंद करें",
        "perf_item_mi_kill_background" to "बैकग्राउंड प्रक्रिया सीमा हटाएँ",
        "perf_item_mi_kill_background_desc" to "background_process_limit=0 फिर am kill-all",
        "perf_item_mi_disable_powerkeeper" to "PowerKeeper सीमा ढीली करें",
        "perf_item_mi_disable_powerkeeper_desc" to "प्रति-कोर पावर चेक सीमा बढ़ाएँ ताकि थ्रॉटलिंग घटे",
        "perf_item_mi_disable_joyose" to "Joyose क्लाउड कंट्रोल रोकें",
        "perf_item_mi_disable_joyose_desc" to "com.xiaomi.joyose बंद करें, गेम FPS स्थिर, वापसी संभव",
        "perf_item_mi_disable_analytics" to "Xiaomi विज्ञापन/एनालिटिक्स बंद करें",
        "perf_item_mi_disable_analytics_desc" to "analytics / mipicks / msa / metoknlp बंद करें, वापसी संभव",
        "perf_item_mi_gpu_tuning" to "गेम टर्बो चालू करें",
        "perf_item_mi_gpu_tuning_desc" to "skiagl रेंडरर बाध्य करें और गेम टर्बो चालू करें",
        "perf_item_mi_ram_expansion_off" to "मेमोरी एक्सटेंशन बंद करें",
        "perf_item_mi_ram_expansion_off_desc" to "ZRAM मेमोरी एक्सटेंशन बंद करें, root चाहिए",
        "perf_item_hw_disable_powergenie" to "Huawei PowerGenie रोकें",
        "perf_item_hw_disable_powergenie_desc" to "com.huawei.powergenie बंद करें, वापसी संभव",
        "perf_item_hw_disable_analytics" to "Huawei एनालिटिक्स रोकें",
        "perf_item_hw_disable_analytics_desc" to "hwaps / bd / microkernel बंद करें, वापसी संभव",
        "perf_item_hw_perf_mode" to "Huawei प्रदर्शन मोड चालू करें",
        "perf_item_hw_perf_mode_desc" to "hw_power_mode=1 लिखें",
        "perf_item_hw_kill_bg" to "Huawei बैकग्राउंड साफ़ करें",
        "perf_item_hw_kill_bg_desc" to "am kill-all से बैकग्राउंड साफ़ करें",
        "perf_item_hw_gpu_turbo" to "GPU Turbo चालू करें",
        "perf_item_hw_gpu_turbo_desc" to "GPU रेंडरिंग बाध्य कर GPU Turbo फ़्लैग लगाएँ, root चाहिए",
        "perf_item_oppo_perf_mode" to "ColorOS प्रदर्शन मोड चालू करें",
        "perf_item_oppo_perf_mode_desc" to "oppo_performance_mode और गेम मोड लिखें",
        "perf_item_oppo_disable_power" to "OPPO पावर गार्ड रोकें",
        "perf_item_oppo_disable_power_desc" to "oppoguardelf बंद करें, वापसी संभव",
        "perf_item_oppo_disable_analytics" to "OPPO लॉग सेवा रोकें",
        "perf_item_oppo_disable_analytics_desc" to "logkit / usageassist बंद करें, वापसी संभव",
        "perf_item_oppo_kill_bg" to "ColorOS बैकग्राउंड साफ़ करें",
        "perf_item_oppo_kill_bg_desc" to "am kill-all से बैकग्राउंड साफ़ करें",
        "perf_item_oppo_disable_osense" to "oSense शेड्यूलिंग रोकें",
        "perf_item_oppo_disable_osense_desc" to "oplus.osense बंद करें, वापसी संभव",
        "perf_item_vivo_perf_mode" to "vivo गेम/प्रदर्शन मोड चालू करें",
        "perf_item_vivo_perf_mode_desc" to "vivo_game_mode और प्रदर्शन मोड लिखें",
        "perf_item_vivo_disable_power" to "vivo पावर मैनेजर रोकें",
        "perf_item_vivo_disable_power_desc" to "com.vivo.pem बंद करें, वापसी संभव",
        "perf_item_vivo_disable_analytics" to "vivo एनालिटिक्स रोकें",
        "perf_item_vivo_disable_analytics_desc" to "abe / bgapp / daemonService बंद करें, वापसी संभव",
        "perf_item_vivo_kill_bg" to "vivo बैकग्राउंड साफ़ करें",
        "perf_item_vivo_kill_bg_desc" to "am kill-all से बैकग्राउंड साफ़ करें",
        "perf_item_vivo_disable_push" to "vivo पुश सेवा रोकें",
        "perf_item_vivo_disable_push_desc" to "vivo पुश सेवा बंद करें; पुश देरी से आ सकते हैं, वापसी संभव",
        "perf_item_ss_perf_mode" to "Samsung प्रदर्शन मोड चालू करें",
        "perf_item_ss_perf_mode_desc" to "samsung_performance_mode और गेम बूस्टर लिखें",
        "perf_item_ss_disable_analytics" to "Samsung एनालिटिक्स रोकें",
        "perf_item_ss_disable_analytics_desc" to "dqagent / diagmonagent / rubin बंद करें, वापसी संभव",
        "perf_item_ss_disable_gos" to "Samsung GOS थ्रॉटलिंग बंद करें",
        "perf_item_ss_disable_gos_desc" to "Game Optimizing Service बंद करें, गेम थ्रॉटल नहीं, वापसी संभव",
        "perf_item_ss_max_refresh" to "Samsung 120Hz बाध्य करें",
        "perf_item_ss_max_refresh_desc" to "peak/min_refresh_rate और refresh_rate_mode लिखें",
        "perf_item_ss_kill_bg" to "Samsung बैकग्राउंड साफ़ करें",
        "perf_item_ss_kill_bg_desc" to "am kill-all से बैकग्राउंड साफ़ करें",
        "perf_item_mz_perf_mode" to "Flyme प्रदर्शन मोड चालू करें",
        "perf_item_mz_perf_mode_desc" to "flyme_performance_mode और गेम मोड लिखें",
        "perf_item_mz_disable_analytics" to "Meizu स्टोर/अपडेटर रोकें",
        "perf_item_mz_disable_analytics_desc" to "mstore / flyme.update बंद करें, वापसी संभव",
        "perf_item_mz_kill_bg" to "Flyme बैकग्राउंड साफ़ करें",
        "perf_item_mz_kill_bg_desc" to "am kill-all से बैकग्राउंड साफ़ करें",
        "perf_item_generic_perf_mode" to "सिस्टम प्रदर्शन/गेम मोड चालू करें",
        "perf_item_generic_perf_mode_desc" to "सामान्य game_mode / performance_mode लिखें",
        "perf_item_generic_kill_bg_brand" to "बैकग्राउंड प्रक्रियाएँ बंद करें",
        "perf_item_generic_kill_bg_brand_desc" to "am kill-all से बैकग्राउंड साफ़ करें",
        "perf_item_generic_disable_analytics" to "इस ब्रांड की एनालिटिक्स रोकें",
        "perf_item_generic_disable_analytics_desc" to "इस ब्रांड के ज्ञात टेलीमेट्री कंपोनेंट बंद करें, वापसी संभव",
    )
}
